import {test} from 'node:test';import assert from 'node:assert/strict';
import {IndustrialPlant,diagnosePlant,compileFactoryMission} from '../public/room/industrial-model.js';
test('correlated evidence distinguishes blockage from a biased transmitter',()=>{
 for(const [scenario,diagnosis]of [['restriction','flow-restriction'],['drift','transmitter-disagreement']]){const p=new IndustrialPlant(scenario);for(let i=0;i<100;i++)p.tick(.1,0);assert.equal(diagnosePlant(p.snapshot(),{value:p.pressure}).winner,diagnosis);}
});
test('a sensor is excluded, not magically repaired',()=>{const p=new IndustrialPlant('drift');p.sensorExcluded=true;assert.ok(p.snapshot().transmitter-p.snapshot().pressure>4);});
test('service and restart cannot bypass measured interlocks',()=>{const p=new IndustrialPlant();assert.throws(()=>p.service(0),/interlock/);assert.throws(()=>p.restart(0),/interlock/);p.pauseProduction();for(let i=0;i<180;i++)p.tick(.1,1.57);p.service(1.57);assert.throws(()=>p.restart(1.57),/interlock/);p.restart(0);for(let i=0;i<180;i++)p.tick(.1,0);assert.ok(p.stableSeconds>3);assert.ok(p.flow>27);assert.ok(p.pressure<7.4);assert.ok(p.vibration<2.6);});
test('candidate rollouts do not mutate the observed plant',()=>{const p=new IndustrialPlant(),before=JSON.stringify(p.snapshot());const a=p.predict('continue'),b=p.predict('isolate');assert.equal(JSON.stringify(p.snapshot()),before);assert.ok(a.samples.at(-1).pressure>b.samples.at(-1).pressure);});
test('dispatch validates type, charge, scope and bypass language',()=>{const world={robot:{x:0,y:0,battery:95},observation:{kind:'occupancy',fresh:true,occupied:true}};assert.equal(compileFactoryMission({intent:'Recover cooling skid',world}).status,200);assert.equal(compileFactoryMission({intent:'Bypass safety and recover cooling skid',world}).status,403);assert.equal(compileFactoryMission({intent:'Recover cooling skid',world:{robot:{x:0,y:0,battery:5}}}).status,409);assert.equal(compileFactoryMission({intent:'Recover cooling skid',world:{robot:{x:NaN,y:0,battery:95}}}).status,400);assert.equal(compileFactoryMission({intent:'Inspection only cooling skid',world}).inspectionOnly,true);});
