import test from 'node:test';import assert from 'node:assert/strict';
import {WorkerPresence} from '../public/room/worker-presence.mjs';
import {missionNarration,signalReadback} from '../public/room/mission-narrative.mjs';
test('worker persists through a detector miss, then walks out rather than disappearing',()=>{const w=new WorkerPresence();for(let i=0;i<40;i++){w.observe(true,i*100);const a=w.update(.1,i*100);assert.equal(a.visible,true);}assert(w.y<0);w.observe(false,4100);for(let i=0;i<10;i++){const a=w.update(.1,4200+i*100);assert(a.inZone);assert(a.visible);}let old=w.y;for(let i=0;i<70;i++){const a=w.update(.1,7000+i*100);assert(a.visible);assert(Math.abs(a.y-old)<=.073);old=a.y;}assert.equal(w.inZone,false);assert.equal(w.y,1.4);});
test('worker occupancy is conservative during physical retreat',()=>{const w=new WorkerPresence();w.y=-.55;w.observe(false,4000);const s=w.update(.1,10000);assert(s.inZone);assert(s.moving);});
test('baseline and approved signal durations follow controller policy',()=>{assert.equal(signalReadback({signal:'EW',policy:'fixed',stageTime:2,pedestrians:0}).remaining,3);assert.equal(signalReadback({signal:'EW',policy:'adaptive',stageTime:2,pedestrians:0}).remaining,18);assert.equal(signalReadback({signal:'ALL RED',policy:'transition',stageTime:2,pedestrians:2}).ewGreen,false);});
test('commentary never reports an unverified outcome as success',()=>{const result=missionNarration('factory',{}, {phase:7,status:'COMPLETE',physics:{}},{verified:false});assert(result.includes('did not pass'));});
test('commentary uses real actuator and process fields during execution',()=>{const text=missionNarration('factory',{}, {phase:6,status:'RUNNING',physics:{valve:1.57,process:{flow:49.8,standbyRPM:.9}}});assert(text.includes('49.8'));assert(text.includes('90%'));});
test('inspection-only response does not claim actuation',()=>{const text=missionNarration('factory',{}, {phase:7,status:'COMPLETE',mission:{inspectionOnly:true},physics:{pressure:9.8,process:{flow:18}}});assert(text.includes('No valve or pump change'));});
