import {chromium} from 'playwright';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:3000',report={checks:[],errors:[]};const assert=(v,s)=>{report.checks.push({name:s,pass:!!v});if(!v)throw Error(s)};
await fs.mkdir('test-report',{recursive:true});const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.errors.push(e.message));
try{
 for(const path of ['/thesis','/operating-stack','/world-model','/robotics','/demos','/roadmap','/why-ajay','/lab']){const r=await page.goto(base+path);assert(r.status()===200,path+' serves 200');assert(await page.locator('.analog-nav a').count()===7,path+' shared navigation');assert(await page.locator('.analog-nav a[aria-current=page]').count()===1,path+' one active section');assert(!(await page.content()).includes('next-project-to-show-physical-ai'),path+' clean public naming');}
 for(const city of [false,true]){const path=city?'/demos/city':'/demos/factory';await page.goto(base+path);await page.waitForFunction(()=>!!window.__operations,{timeout:90000});assert(await page.locator('.map-asset').count()>=24,path+' rich topology');
 for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(250);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),path+' no overflow at '+width);await page.screenshot({path:'test-report/'+(city?'city':'factory')+'-'+width+'.png',fullPage:true});}
 await page.setViewportSize({width:1440,height:1000});await page.locator('#opsSelect').selectOption(city?'J-03':'P-101');assert(await page.locator('#opsInspector').innerText().then(s=>s.includes(city?'J-03':'P-101')),'selected asset state');
 await page.locator('#opsIntent').fill(city?'Reduce congestion at J-03':'Inspect P-101');await page.locator('#opsCommand button').click();assert(await page.locator('[data-release]').isVisible(),'plan requires release');await page.locator('[data-release]').click();await page.locator('[data-hold]').click();const elapsed=await page.evaluate(()=>window.__operations.state().mission.elapsed);await page.waitForTimeout(1100);assert(await page.evaluate(()=>window.__operations.state().mission.elapsed)===elapsed,'hold stops model mission');await page.locator('[data-hold]').click();await page.waitForFunction(()=>window.__operations.state().mission.status==='COMPLETE',{timeout:30000});assert(await page.evaluate(()=>window.__operations.state().mission.evidence.length)>3,'mission records evidence');
 await page.locator('#opsWorldModel').click();await page.locator('[data-tab=prediction]').click();assert(await page.locator('#wmBody svg').count()===1,'counterfactual chart rendered');await page.locator('[data-tab=memory]').click();assert(await page.locator('#wmTimeline').isVisible(),'episode replay available');await page.locator('#wmClose').click();
 await page.locator('#opsRuntimeLink').click();await page.waitForFunction(c=>c?window.__city?.state().ready:window.__room?.state().ready,city,{timeout:90000});assert(await page.locator(city?'#cityScene canvas':'#scene canvas').isVisible(),'retained 3D runtime visible');await page.screenshot({path:'test-report/'+(city?'city':'factory')+'-runtime.png',fullPage:true});
 }
 assert(report.errors.length===0,'no uncaught browser errors');report.pass=true;
}catch(e){report.pass=false;report.failure=e.message;await page.screenshot({path:'test-report/failure.png',fullPage:true});process.exitCode=1;}finally{await fs.writeFile('test-report/operations.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));}
