import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:3003';await fs.mkdir('test-report',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const results=[];
const data=p=>p.evaluate(()=>({s:(window.__city||window.__room).state(),d:window.__demoDirector.state(),p:window.__showcase.state(),camera:window.__showcaseCamera.state(),dialogs:document.querySelectorAll('dialog[open]').length}));
try{
 for(const kind of ['factory','city']){
  const p=await browser.newPage({viewport:{width:1366,height:768},acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`${base}/demos/${kind}?mode=live`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelector('#plRun')?.disabled===false,{}, {timeout:120000});await p.waitForTimeout(1800);
  assert.equal(await p.locator('#plShowcase .pl-card').count(),3);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&document.documentElement.scrollHeight<=innerHeight+1),'Laptop overflow');
  const layout=await p.evaluate(()=>[...document.querySelectorAll('.pl-card')].map(e=>({height:e.clientHeight,scroll:e.scrollHeight,b:e.getBoundingClientRect().bottom})));assert(layout.every(e=>e.scroll<=e.height+1&&e.b<=innerHeight+1),'Core cards require scrolling: '+JSON.stringify(layout));
  assert.equal(await p.locator('#plFeedSlot canvas').count(),1,'Executor camera must be visible');const stage=await p.locator('#plStage').boundingBox();assert(stage.width>600&&stage.height>350);
  await p.screenshot({path:`test-report/${kind}-clean-ready.png`});
  await p.locator('[data-pl-ask]').first().click();assert((await p.locator('#plReply').innerText()).length>10);
  await p.locator('#plRun').click();const start=Date.now();let complete=null,approved=false,flightSeen=false,flightFrames=0,visibleFlight=0;
  while(Date.now()-start<240000){const x=await data(p);assert.equal(x.dialogs,0,'No blocking or blurring dialog');if(x.s.scene?.drone?.state&&['Taking off','Scanning junction','Returning'].includes(x.s.scene.drone.state)){flightSeen=true;flightFrames++;if(x.camera?.onScreen)visibleFlight++;}
   if(x.s.status==='AWAITING APPROVAL'&&!approved){await p.waitForTimeout(700);assert.equal((await data(p)).s.status,'AWAITING APPROVAL','Approval may not silently advance');await p.screenshot({path:`test-report/${kind}-clean-approval.png`});await p.locator('#plNext').click();approved=true;}
   if(x.d.finished){complete=x;break;}if(['ERROR','BLOCKED','FAILED'].includes(x.s.status))throw Error(JSON.stringify(x.s.events.slice(-4)));await p.waitForTimeout(240);
  }
  if(!complete){await fs.writeFile(`test-report/${kind}-timeout.json`,JSON.stringify(await data(p),null,2));throw Error(kind+' timed out');}
  assert.equal(complete.d.finished.verified,true);assert(complete.s.events.some(e=>e.layer==='APPROVAL'&&e.detail?.actor==='operator'));if(flightSeen)assert(visibleFlight/flightFrames>.85,'Drone leaves camera too often');await p.screenshot({path:`test-report/${kind}-clean-complete.png`});
  const download=p.waitForEvent('download');await p.locator('#plExport').click();const file=await download;await file.saveAs(`test-report/${kind}-evidence.json`);const payload=JSON.parse(await fs.readFile(`test-report/${kind}-evidence.json`));assert(payload.frames.length>5&&payload.controller.events.length>0);
  await p.locator('#plReset').click();await p.waitForFunction(()=>document.querySelector('#plRun')?.disabled===false);await p.selectOption('#plMode','step');await p.locator('#plRun').click();await p.waitForFunction(()=>window.__showcase.state().pending===0);const before=await data(p);await p.waitForTimeout(1400);const after=await data(p);assert.equal(after.p.pending,0);assert.equal(after.s.paused,false,'A step explanation must not pause the environment');assert(after.p.frame.revision>before.p.frame.revision);assert.equal(after.dialogs,0);await p.screenshot({path:`test-report/${kind}-nonblocking-step.png`});await p.locator('#plNext').click();await p.waitForFunction(()=>window.__showcase.state().pending===1);await p.locator('[data-pl-open="world"]').click();await p.waitForTimeout(700);assert.equal(await p.locator('dialog[open]').count(),0);await p.screenshot({path:`test-report/${kind}-live-source-drawer.png`});await p.locator('#plCloseDrawer').click();await p.locator('#plStop').click();await p.waitForFunction(()=>['STOPPED','BLOCKED'].includes((window.__city||window.__room).state().status));
  await p.setViewportSize({width:390,height:844});await p.waitForTimeout(500);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:`test-report/${kind}-mobile-clean.png`,fullPage:true});
  assert.deepEqual(errors,[]);results.push({kind,verified:true,flightSeen,flightFrames,visibleFlight,seconds:Math.round((Date.now()-start)/1000),layout,errors});console.log(JSON.stringify(results.at(-1)));await p.close();
 }
}catch(e){for(const p of browser.contexts().flatMap(c=>c.pages())){await p.screenshot({path:'test-report/showcase-failure.png',fullPage:true}).catch(()=>{});await fs.writeFile('test-report/showcase-failure.json',JSON.stringify(await data(p).catch(()=>({})),null,2)).catch(()=>{});}throw e;}finally{await fs.writeFile('test-report/showcase-results.json',JSON.stringify(results,null,2));await browser.close();}
