import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:3000';
const dir='test-report';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-dev-shm-usage']});
const report={date:new Date().toISOString(),environment:'Chromium / actual Next route handlers',checks:[],errors:[],missions:[]};
const assert=(v,message)=>{report.checks.push({name:message,pass:Boolean(v)});if(!v)throw Error(message);};
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
page.on('pageerror',e=>report.errors.push(String(e)));
const ready=async city=>{await page.goto(base+(city?'/city.html':'/studio.html'),{waitUntil:'domcontentloaded'});await page.waitForFunction(c=>c?window.__city?.state().ready:window.__room?.state().ready,city,{timeout:150000});await page.waitForTimeout(1200);};
const screenshot=async name=>page.screenshot({path:dir+'/'+name+'.png'});
const s=city=>page.evaluate(c=>c?window.__city.state():window.__room.state(),city);
async function checkLayout(city){for(const size of [[1440,900],[1366,768],[1728,895]]){await page.setViewportSize({width:size[0],height:size[1]});await page.waitForTimeout(500);const box=await page.evaluate(c=>{const rail=document.querySelector(c?'#stackList':'#layerList'),decision=document.querySelector(c?'.decision':'.decision-card'),last=rail.lastElementChild.getBoundingClientRect(),d=decision.getBoundingClientRect();return{gap:d.top-last.bottom,w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight,vw:innerWidth,vh:innerHeight,scene:document.querySelector(c?'.stage':'.world-panel').getBoundingClientRect().width};},city);assert(box.gap>=0,'No stack/status collision '+city+' '+size.join('x'));assert(box.w<=box.vw+1,'No horizontal overflow '+size.join('x'));assert(box.h<=box.vh+2,'Desktop single-screen fit '+size.join('x'));assert(box.scene>400,'Live render remains prominent');await screenshot((city?'city':'factory')+'-'+size.join('x'));}
await page.setViewportSize({width:1440,height:900});await page.locator('[data-layer="2"]').first().click();await page.waitForTimeout(300);assert(await page.locator('#ucPopover').isVisible(),'Layer opens compact inspector');const collision=await page.evaluate(c=>{const a=document.querySelector('#ucPopover').getBoundingClientRect(),b=document.querySelector(c?'.stage':'.world-panel').getBoundingClientRect();return a.left>=b.right-1;},city);assert(collision,'Popup never covers scene');await screenshot((city?'city':'factory')+'-popup');await page.locator('[data-close]').click();
await page.locator('[data-signals]').first().click();await page.waitForTimeout(500);await screenshot((city?'city':'factory')+'-signals');await page.locator('[data-close]').click();
await page.selectOption('#ucEntity',city?'D-01':'R-07');await page.locator('[data-skill="'+(city?'survey':'navigate')+'"]').click();await page.waitForTimeout(300);await screenshot((city?'city':'factory')+'-skill');await page.locator('[data-close]').click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile no horizontal overflow');await screenshot((city?'city':'factory')+'-mobile');await page.setViewportSize({width:1440,height:900});}
async function mission(city){const started=Date.now();await page.locator(city?'#runCity':'#runBtn').click();let approved=false,complete=false;const snapshots=[];while(Date.now()-started<295000){const st=await s(city);if(!approved&&await page.locator('#approval').isVisible()){await screenshot((city?'city':'factory')+'-approval');await page.locator(city?'#approveCity':'#approveBtn').click();approved=true;}if(st.phase===6&&snapshots.length===0){snapshots.push(st);await screenshot((city?'city':'factory')+'-acting');}if(st.status==='COMPLETE'){complete=true;break;}if(['BLOCKED','STOPPED','ERROR','FAILED'].includes(st.status))throw Error((city?'City':'Factory')+' blocked: '+JSON.stringify(st.events.slice(-5)));await page.waitForTimeout(600);}const st=await s(city);report.missions.push({kind:city?'city':'factory',seconds:(Date.now()-started)/1000,approved,complete,result:st.result,physics:st.physics,scene:st.scene,events:st.events.map(e=>({layer:e.layer,text:e.text,detail:e.detail})),episodes:st.episodes});assert(complete,(city?'City':'Factory')+' completed under five minutes');assert(approved,'Scoped approval actually exercised');if(!city){assert(st.runtime==='MuJoCo','Factory uses MuJoCo, no fallback');assert(st.physics.valve>1.45,'V-12 feedback confirms isolation');assert(st.physics.process.flow>45,'Standby flow restored');assert(st.physics.process.standbyRPM>.9,'Standby RPM measured');assert(st.physics.process.workOrder.status.includes('Contained'),'Work order remains pending for duty repair');assert(st.events.some(e=>e.layer==='DIAGNOSIS'),'Diagnostic evidence recorded');assert(st.events.some(e=>e.layer==='ROLLOUT'),'Response comparison recorded');}
await screenshot((city?'city':'factory')+'-complete');}
try{
 await ready(true);await checkLayout(true);await mission(true);
 await ready(false);await page.waitForFunction(()=>window.__room.state().observation?.fresh,null,{timeout:120000});await page.waitForFunction(()=>window.__console.state().loadingVideo.ready,null,{timeout:60000});assert(true,'New recorded warehouse video decoded');await checkLayout(false);await mission(false);
 await page.selectOption('#ucCase','instrument');await page.waitForTimeout(600);await page.locator('#runBtn').click();let instrumentDone=false;const at=Date.now();while(Date.now()-at<230000){const st=await s(false);assert(!(await page.locator('#approval').isVisible()),'Instrument audit does not actuate');if(st.status==='COMPLETE'){instrumentDone=true;break;}if(['BLOCKED','STOPPED'].includes(st.status))throw Error('Instrument audit held');await page.waitForTimeout(1500);}const audit=await s(false);report.missions.push({kind:'instrument-audit',seconds:(Date.now()-at)/1000,complete:instrumentDone,physics:audit.physics});assert(instrumentDone,'Instrument-disagreement workflow completes');assert(audit.physics.valve<.1,'Instrument audit leaves valve open');assert(audit.physics.process.standbyRPM<.01,'Audit never starts standby');assert(audit.physics.process.diagnosis.cause.includes('disagreement'),'Sensor disagreement identified');await screenshot('factory-instrument-audit');
 assert(report.errors.length===0,'No uncaught browser errors');
 report.pass=true;
}catch(e){report.pass=false;report.failure=String(e);try{report.lastState=await page.evaluate(()=>({factory:window.__room?.state(),city:window.__city?.state(),ui:window.__console?.state()}));await screenshot('failure');}catch{}console.error(e);process.exitCode=1;}
finally{await fs.writeFile(dir+'/unified-verification.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pass:report.pass,failure:report.failure,missions:report.missions.map(m=>({kind:m.kind,seconds:m.seconds,complete:m.complete})),checks:report.checks.length,errors:report.errors},null,2));}
