import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:3003',dir='test-report/experience';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const errors=[];const page=await browser.newPage({viewport:{width:1440,height:960}});page.on('pageerror',e=>errors.push(e.message));
async function open(route){const r=await page.goto(base+'/'+route,{waitUntil:'networkidle'});assert.equal(r.status(),200,route);await page.waitForFunction(()=>window.__lightReady);}
try{
 for(const route of ['thesis','operating-stack','world-model','robotics','demos','roadmap','why-ajay']){await open(route);assert.equal(await page.locator('.scene-story').count(),0,'No scroll traps');assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('main img').count(),0,'No moving image artwork');assert.equal(await page.locator('.technical-details').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow: '+route);if(await page.locator('[data-machine-view]').count()){await page.locator('[data-machine-view]').first().scrollIntoViewIfNeeded();await page.waitForFunction(()=>window.__engineeringViews?.get().some(v=>v.ready==='true'));const views=await page.evaluate(()=>window.__engineeringViews.get());assert(views[0].meshes>35,route+' mesh detail: '+JSON.stringify(views));}
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${dir}/${route}.png`,fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow: '+route);await page.screenshot({path:`${dir}/${route}-mobile.png`,fullPage:true});await page.setViewportSize({width:1440,height:960});}
 await open('operating-stack');assert.equal(await page.locator('#archRows [data-row]').count(),6);const aligned=await page.locator('.arch-row').evaluateAll(rows=>rows.map(r=>{const a=r.querySelector('.arch-rail').getBoundingClientRect(),b=r.querySelector('.arch-band').getBoundingClientRect();return Math.abs(a.y-b.y)+Math.abs(a.height-b.height)}));assert(aligned.every(v=>v<1),JSON.stringify(aligned));assert((await page.locator('#architecture').boundingBox()).y<270,'Stack is immediately below header');await page.locator('[data-module="native-1"]').click();assert(await page.locator('#detailDrawer').isVisible());assert((await page.locator('#drawerContent').innerText()).includes('Input'));await page.locator('#drawerClose').click();await page.locator('[data-action="run"]').first().click();await page.waitForFunction(()=>window.__light.getState().phase===3);assert.equal(await page.evaluate(()=>window.__light.getState().approved),false);await page.locator('[data-action="approve"]').first().click();await page.waitForFunction(()=>window.__light.getState().complete,{}, {timeout:45000});assert((await page.evaluate(()=>window.__light.getState())).flow>45);
 await open('robotics');await page.waitForFunction(()=>window.__engineeringViews?.get().length);for(const type of ['drone','arm','ground']){await page.locator(`[data-embodiment="${type}"]`).click();await page.waitForFunction(k=>window.__engineeringViews.get().some(v=>v.kind===k),type);assert.equal(await page.locator('#robotChain button').count(),6);}const camera=await page.evaluate(()=>window.__engineeringViews.get()[0].camera);const r=await page.locator('.runtime-model canvas').boundingBox();await page.mouse.move(r.x+r.width*.45,r.y+r.height*.5);await page.mouse.down();await page.mouse.move(r.x+r.width*.67,r.y+r.height*.6,{steps:14});await page.mouse.up();await page.waitForTimeout(500);assert.notDeepEqual(await page.evaluate(()=>window.__engineeringViews.get()[0].camera),camera,'True 3D orbit changes camera');
 await open('world-model');await page.locator('#expireSource').click();await page.locator('#compareFutures').click();assert.equal(await page.locator('#recoverPrediction').innerText(),'Held');await page.locator('#refreshSource').click();await page.locator('#compareFutures').click();assert((await page.locator('#recoverPrediction').innerText()).includes('L/min'));
 assert.deepEqual(errors,[]);console.log('PASS: full stack visible, six aligned rows, interactive mesh assemblies, partner details, scoped actions, mobile layouts and evidence gates.');
}catch(e){await page.screenshot({path:`${dir}/failure.png`,fullPage:true});throw e;}finally{await fs.writeFile(`${dir}/errors.json`,JSON.stringify(errors));await browser.close();}
