import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:3003',dir='test-report/architecture';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const routes=['thesis','operating-stack','world-model','robotics','demos','roadmap','why-ajay'];
async function open(route){const r=await page.goto(base+'/'+route,{waitUntil:'networkidle'});assert.equal(r.status(),200,route+' status');}
try{
 const titles=new Set(),heads=new Set();
 const markers={thesis:'.mission-orbit','operating-stack':'.reference-blueprint','world-model':'.world-stage',robotics:'.robotics-stage',demos:'.demo-posters',roadmap:'.roadmap-machine','why-ajay':'.career-signal'};
 for(const route of routes){await open(route);const title=await page.title(),h=await page.locator('h1').first().innerText();assert(!titles.has(title)&&!heads.has(h),'Each route needs a distinct story');titles.add(title);heads.add(h);assert.equal(await page.locator(markers[route]).count(),1,route+' unique visual');assert.equal(await page.locator('.site-nav nav a').count(),7);assert.equal(await page.locator('.site-nav nav [aria-current=page]').getAttribute('href'),'/'+route);const body=await page.locator('body').innerText();assert(!/\b(?:Analog|Hive|Etisalat|Hassantuk)\b|e&\s/i.test(body),route+' restricted branding');assert.equal(await page.locator('.physical-story').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' desktop overflow');await page.screenshot({path:dir+'/'+route+'.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' mobile overflow');await page.screenshot({path:dir+'/'+route+'-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:960});}
 await open('operating-stack');assert.equal(await page.locator('[data-ref-band]').count(),6);assert.equal(await page.locator('.integration-rail [data-integration]').count(),6);assert((await page.locator('.module-card').count())>=14);assert((await page.locator('[data-partner]').count())>=8);
 await page.locator('[data-partner="alphaz"]').first().click();assert.equal(await page.locator('#partnerDrawer').getAttribute('hidden'),null);assert.match(await page.locator('#partnerName').innerText(),/AlphaZ/);assert((await page.locator('#partnerPublished li').count())>=3);assert(/^https:/.test(await page.locator('#partnerSource').getAttribute('href')));await page.screenshot({path:dir+'/reference-partner.png',fullPage:false});await page.locator('#partnerClose').click();
 await page.locator('#refPlay').click();await page.waitForFunction(()=>document.querySelectorAll('[data-ref-band][data-active="true"]')[0]?.dataset.refBand==='1',{timeout:5000});await page.locator('#refPlay').click();const held=await page.locator('[data-ref-band][data-active="true"]').getAttribute('data-ref-band');await page.waitForTimeout(1500);assert.equal(await page.locator('[data-ref-band][data-active="true"]').getAttribute('data-ref-band'),held);await page.locator('#refReset').click();assert.equal(await page.locator('[data-ref-band][data-active="true"]').getAttribute('data-ref-band'),'0');
 await open('world-model');await page.locator('#staleState').click();assert.match(await page.locator('#worldFlowValue').innerText(),/Unknown/);await page.locator('#worldPredict').click();assert.equal(await page.locator('#futureCandidate').innerText(),'Held');await page.locator('#freshState').click();await page.locator('#worldPredict').click();assert.equal(await page.locator('#futureCandidate').innerText(),'58 L/min');await page.locator('[data-world-node="V-12"]').click();assert.match(await page.locator('#worldNodeDetail').innerText(),/authority/i);
 await open('robotics');const seen=[];for(const v of ['ground','drone','arm']){await page.locator('[data-embodiment="'+v+'"]').click();const titles=await page.locator('[data-robot-stack="'+v+'"] h3').allInnerTexts();seen.push(titles.join('|'));assert.equal(titles.length,6);await page.locator('[data-robot-stack="'+v+'"] [data-robot-layer="4"]').click();assert.match(await page.locator('#robotDetailTitle').innerText(),v==='drone'?/Flight control/:v==='arm'?/Servo/:/Control/);await page.screenshot({path:dir+'/robotics-'+v+'.png',fullPage:false});}assert.equal(new Set(seen).size,3);
 await open('roadmap');const phase=[];for(let i=0;i<4;i++){await page.locator('[data-roadmap="'+i+'"]').click();phase.push(await page.locator('#roadmapDetail h2').innerText());}assert.equal(new Set(phase).size,4);
 await open('demos');assert.equal(await page.locator('.demo-poster').count(),2);assert.equal(await page.locator('.demo-poster.factory').getAttribute('href'),'/demos/factory?mode=live');assert.equal(await page.locator('.demo-poster.city').getAttribute('href'),'/demos/city?mode=live');
 for(const demo of ['factory','city']){const r=await page.request.get(base+'/demos/'+demo);assert.equal(r.status(),200);const html=await r.text();assert(html.includes('/room/showcase.js'));assert(!html.includes('/architecture-explorer.css'),'Architecture redesign must not modify demo runtime: '+demo);}
 const rel=await (await page.request.get(base+'/release.json')).json();assert.equal(rel.release,'2026-10-04.7');assert(rel.features.includes('deep-partner-architecture'));
 assert.deepEqual(errors,[]);console.log('PASS: seven distinct visual narratives, deep partner reference stack, world-state interactions, three embodiment architectures, roadmap, mobile fit, and untouched live demos.');
}catch(e){await page.screenshot({path:dir+'/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await fs.writeFile(dir+'/errors.json',JSON.stringify(errors,null,2));await browser.close();}
