import fs from 'node:fs/promises';
import {nav,partners,reference,robotLayers,world,cases} from './catalog.mjs';
import {referenceModules,partnerDepth,integrationRail,pageStory,thesisBets} from './depth.mjs';

const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(href,label,cls='')=>`<a class="${cls}" href="${href}"${cls.includes('active')?' aria-current="page"':''}>${label}</a>`;
const header=active=>`<a class="skip-link" href="#main">Skip to content</a><header class="site-nav"><a class="site-brand" href="/thesis"><span>Physical Ops Lab</span><small>INDEPENDENT PHYSICAL AI PRODUCT THESIS</small></a><nav aria-label="Primary navigation">${nav.map(([href,label])=>link(href,e(label),href===active?'active':'')).join('')}</nav><a class="demo-jump" href="/demos/factory?mode=live">Live demo ↗</a></header>`;
const footer=`<footer class="site-footer"><span>AJAY CYRIL / PHYSICAL OPS LAB</span><span>Independent proposal · simulations and proposed partner roles are explicitly labelled.</span></footer>`;
const shell=(slug,title,desc,body,cls='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${e(desc)}"><meta name="theme-color" content="#f3f4f0"><title>${e(title)} | Physical Ops Lab</title><link rel="canonical" href="https://physical-ops-lab.vercel.app/${slug}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/architecture-explorer.css"><script type="module" src="/architecture-explorer.js"></script><script type="module" src="/architecture-motion.js"></script></head><body class="${cls}" data-page="${slug}">${header('/'+slug)}<main id="main">${body}</main>${footer}<aside id="partnerDrawer" class="partner-drawer" aria-live="polite" hidden><button id="partnerClose" class="drawer-close" aria-label="Close partner detail">×</button><span class="eyebrow" id="partnerRole">PROPOSED PARTNER</span><h2 id="partnerName"></h2><p id="partnerFit"></p><div id="partnerPublished" class="drawer-section"></div><div class="drawer-section"><span>INTEGRATION BOUNDARY</span><p id="partnerBoundary"></p></div><a id="partnerSource" target="_blank" rel="noopener noreferrer">Published source ↗</a></aside></body></html>`;

const hero=(k,title,desc,extra='')=>`<section class="page-hero" data-reveal><div><span class="eyebrow">${k}</span><h1>${title}</h1><p>${desc}</p>${extra}</div><div class="hero-mark" data-parallax=".04" aria-hidden="true"><i></i><i></i><i></i><i></i></div></section>`;

const partnerButtons=keys=>keys.map(k=>`<button class="partner-pill" data-partner="${k}"><b>${e(partners[k].name)}</b><span>${e(partners[k].role)}</span></button>`).join('');
const moduleCards=(mods,layerIndex)=>mods.map((m,i)=>`<article class="module-card" data-ref-module="${layerIndex}" data-module-index="${i}"${m.partner?` data-partner-key="${m.partner}"`:''}><header><span>${e(m.subtitle)}</span><b>${e(m.title)}</b></header><p>${e(m.body)}</p><div>${m.chips.map(c=>`<span>${e(c)}</span>`).join('')}</div>${m.partner?`<button data-partner="${m.partner}">Partner detail ↗</button>`:''}</article>`).join('');

const refLayers=[
  ['intent','CUSTOMER LAYER','Customer & mission',referenceModules.intent],
  ['applications','APPLICATION LAYER','Domain applications',referenceModules.applications],
  ['intelligence','AI INTELLIGENCE','Perception, reasoning & prediction',referenceModules.intelligence],
  ['orchestration','ORCHESTRATION','Cross-fleet mission control',referenceModules.orchestration],
  ['native','NATIVE PLATFORMS','Fleet-native autonomy',referenceModules.native],
  ['fleets','PHYSICAL FLEETS','Robots, drones & infrastructure',referenceModules.fleets]
];

const referenceBlueprint=`<section class="reference-blueprint" id="referenceBlueprint" data-reveal>
  <div class="blueprint-head"><div><span class="eyebrow">INTERACTIVE REFERENCE ARCHITECTURE</span><h2>Enterprise intent to physical execution.</h2><p>Modeled on the multi-layer pattern you shared: applications above intelligence, orchestration above native platforms, then physical fleets—connected by explicit mission and evidence contracts.</p></div><div class="blueprint-actions"><button id="refPlay" class="primary">▶ Play the flow</button><button id="refReset">↺ Reset</button></div></div>
  <div class="blueprint-layout">
    <div class="layer-rail" aria-label="Architecture layers">${refLayers.map(([id,label],i)=>`<button data-ref-layer="${i}"><span>LAYER ${String(6-i).padStart(2,'0')}</span><b>${label}</b><i></i></button>`).join('')}<button class="rail-legend" data-ref-layer="all"><b>How to read</b><span>Mission ↓ · telemetry & evidence ↑</span></button></div>
    <div class="blueprint-core">
      ${refLayers.map(([id,label,title,mods],i)=>`<section class="ref-band band-${id}" data-ref-band="${i}" id="ref-${id}" data-reveal>
        <div class="band-label"><span>${label}</span><h3>${title}</h3><p>${e(reference[i].summary)}</p></div>
        <div class="band-modules">${moduleCards(mods,i)}</div>
        <i class="band-pulse" aria-hidden="true"></i>
      </section>`).join('')}
      <div class="contract-bus"><span>MISSION INTENT ↓</span><b>SHARED CONTRACT BUS</b><span>↑ TELEMETRY · VIDEO · EVIDENCE</span></div>
    </div>
    <aside class="integration-rail" data-reveal><span class="eyebrow">INTEGRATIONS</span><h3>Enterprise edges</h3>${integrationRail.map(([a,b,c])=>`<button data-integration><b>${e(a)}</b><span>${e(b)}</span><small>${e(c)}</small></button>`).join('')}<div class="api-card"><span>MISSION API</span><b>Typed goals, status, evidence</b><code>POST /missions<br>GET /missions/:id<br>WEBHOOK /events</code></div></aside>
  </div>
  <div class="blueprint-caption"><span id="refStatus">Select a layer, module or partner. Nothing on this page calls a partner API.</span><span>Mission ↓ · evidence ↑</span></div>
</section>`;

const partnerMatrix=`<section class="ecosystem section-block" data-reveal><div class="section-head"><div><span class="eyebrow">PROPOSED ECOSYSTEM</span><h2>Partner deeply. Couple loosely.</h2></div><p>Every partner card opens the published capability, proposed role, and the integration boundary that prevents the stack becoming a set of one-off projects.</p></div><div class="partner-matrix">${Object.keys(partnerDepth).slice(0,8).map(k=>`<button data-partner="${k}"><span>${e(partners[k]?.role||'Reference capability')}</span><b>${e(partners[k]?.name||k)}</b><i>Open architecture ↗</i></button>`).join('')}</div></section>`;

const thesisSteps=pageStory.thesis.map(([n,t,d],i)=>`<article class="mission-beat" data-story-beat="${i}" data-reveal><span>${n}</span><div><h3>${t}</h3><p>${d}</p></div><i></i></article>`).join('');
const thesis=`<section class="thesis-hero" data-reveal>
  <div class="thesis-copy"><span class="eyebrow">PRODUCT THESIS / AJAY CYRIL</span><h1>Physical AI becomes a product when the loop closes.</h1><p>A natural-language goal is useful only when the system can ground it in a live world state, coordinate the right capability, act within clear authority, and prove the physical result.</p><div class="hero-actions">${link('/demos/factory?mode=live','Run the live system ↗','primary-link')}${link('/operating-stack','Explore the reference stack →')}</div></div>
  <div class="mission-orbit" data-parallax=".08" aria-label="Physical AI operating loop"><div class="orbit-core"><span>MISSION</span><b>GOAL → EVIDENCE</b></div>${[['Agent','Intent'],['World','State'],['Mission','Policy'],['Robot','Action'],['Evidence','Verify']].map((x,i)=>`<div class="orbit-node n${i}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<i class="orbit-line l1"></i><i class="orbit-line l2"></i><i class="orbit-line l3"></i></div>
</section>
<section class="story-ribbon" data-reveal><div class="story-track" data-parallax=".02">${thesisSteps}</div></section>
<section class="bets section-block" data-reveal><div class="section-head"><div><span class="eyebrow">FOUR PRODUCT BETS</span><h2>Where I would place the moat.</h2></div><p>Not every layer deserves proprietary technology. The product advantage should sit where trust, reuse and operating data compound.</p></div><div class="bet-grid">${thesisBets.map(([k,p],i)=>`<article><span>0${i+1} / ${e(k)}</span><p>${e(p)}</p></article>`).join('')}</div></section>
<section class="architecture-doors section-block" data-reveal>${[['Reference stack','Applications → intelligence → orchestration → native platforms → fleets','/operating-stack'],['World model','Observations → entities → state → memory → prediction','/world-model'],['Robotics stack','Mission → skills → perception → planning → local control → feedback','/robotics']].map(([t,p,h])=>`<a href="${h}"><span>ARCHITECTURE</span><h2>${t}</h2><p>${p}</p><b>Open →</b></a>`).join('')}</section>`;

const operating=`${hero('01 / REFERENCE STACK','A production architecture has seams. Make them explicit.','The reference stack shows exactly where customer workflow ends, intelligence begins, orchestration owns the mission, native platforms retain autonomy, and physical fleets return evidence.')}${referenceBlueprint}${partnerMatrix}<section class="ownership section-block" data-reveal><div class="section-head"><div><span class="eyebrow">OWN / BUY / PARTNER</span><h2>The architecture decision is the product decision.</h2></div></div><div class="ownership-grid"><article><span>OWN</span><h3>Goal + world context</h3><p>Mission identity, asset identity, authority, acceptance criteria, evidence and learning loop.</p></article><article><span>BUY / INTEGRATE</span><h3>Mature fleet operations</h3><p>Fleet visibility, teleoperation, configuration and native autonomy where a proven platform already exists.</p></article><article><span>PARTNER</span><h3>Embodiments + specialist AI</h3><p>Robots, drones, edge compute and domain models behind versioned capability and observation interfaces.</p></article></div></section>`;

const worldFlow=`<section class="world-stage" data-reveal><div class="world-toolbar"><div><span class="eyebrow">ILLUSTRATIVE LIVE STATE</span><h2>P-204 cooling circuit</h2></div><div><button id="freshState" class="primary">Fresh observation</button><button id="staleState">Expire source</button><button id="worldPredict">Compare futures</button></div></div>
<div class="world-layout">
  <section class="event-stream"><span class="panel-label">OBSERVATIONS</span><article data-event="camera"><i></i><div><b>CAM-01</b><p>Person detected in service aisle</p><small>source: recorded video · frame 284</small></div></article><article data-event="flow"><i></i><div><b>FT-02</b><p id="worldFlowValue">18 L/min cooling flow</p><small id="worldFlowFresh">OBSERVED · sample 001</small></div></article><article data-event="pressure"><i></i><div><b>PT-04</b><p>9.4 bar pressure</p><small>SIMULATED SENSOR · fresh</small></div></article></section>
  <section class="entity-scene" data-parallax=".025"><span class="panel-label">OPERATIONAL WORLD STATE</span><div class="entity-map"><button data-world-node="P-204" class="pump"><span>P-204</span><b>Duty pump</b></button><button data-world-node="V-12" class="valve"><span>V-12</span><b>Isolation valve</b></button><button data-world-node="SB-02" class="standby"><span>SB-02</span><b>Standby</b></button><button data-world-node="R-07" class="robot"><span>R-07</span><b>Inspector</b></button><i class="pipe p1"></i><i class="pipe p2"></i><i class="route"></i></div><div id="worldNodeDetail" class="entity-detail"><span>ENTITY / P-204</span><p>Current belief: low flow + elevated pressure. Diagnosis remains unconfirmed until inspection.</p></div></section>
  <section class="future-panel"><span class="panel-label">PREDICTION / GOVERNANCE</span><div class="future-card"><small>CURRENT</small><b id="futureCurrent">18 L/min</b><p>Duty circuit constrained.</p></div><div class="future-vs">VS</div><div class="future-card candidate"><small>CANDIDATE</small><b id="futureCandidate">Not evaluated</b><p id="futureDetail">Select Compare futures.</p></div><div class="world-rule"><span>RULE</span><p>Prediction can propose. It cannot overwrite observed state or grant authority.</p></div></section>
</div></section>`;
const worldChapters=`<section class="world-chapters section-block">${pageStory.world.map(([t,d],i)=>`<article data-reveal><span>0${i+1}</span><h3>${e(t)}</h3><p>${e(d)}</p><i></i></article>`).join('')}</section>`;
const worldPage=`${hero('02 / WORLD MODEL','A shared world. Not a shared guess.','Operational world state, memory and learned prediction are different products. This page makes the authority boundary visible.')}${worldFlow}${worldChapters}<section class="model-routing section-block" data-reveal><div class="section-head"><div><span class="eyebrow">MODEL ROUTING THESIS</span><h2>General first. Specialist when it earns its place.</h2></div><p>As capable multimodal models get cheaper, much narrow video semantics can move behind one general interface. Keep a specialist only where event-level quality, latency, offline operation, privacy or total cost is materially better.</p></div><div class="routing-flow"><span>cheap edge trigger</span><i>→</i><span>selected evidence</span><i>→</i><b>general VLM</b><i>→</i><span>world context</span><i>→</i><span>mission</span></div><div class="route-partners">${partnerButtons(['levatas','cosmos','optelos','observance'])}</div></section>`;

const robotLane=(variant,layers)=>`<div class="robot-stack" data-robot-stack="${variant}"${variant==='ground'?'':' hidden'}>${layers.map((l,i)=>`<button class="robot-layer" data-robot-layer="${i}"><span>0${i+1}</span><div><small>${e(l.tag)}</small><h3>${e(l.name)}</h3><p>${e(l.summary)}</p></div><i>↗</i></button>`).join('')}</div>`;
const robotVisual=`<section class="robotics-stage" data-reveal><div class="embodiment-tabs" role="tablist"><button data-embodiment="ground" aria-selected="true">Ground robot</button><button data-embodiment="drone">Drone + dock</button><button data-embodiment="arm">Manipulator</button></div><div class="robotics-layout">
<section class="embodiment-visual" data-parallax=".03"><div id="robotSilhouette" class="silhouette ground"><span class="sensor">SENSORS</span><span class="compute">EDGE COMPUTE</span><span class="runtime">SKILL RUNTIME</span><span class="control">LOCAL CONTROL</span><i></i><i></i><i></i></div><div class="boundary-label"><b>LOCAL SAFETY BOUNDARY</b><span>Cloud orchestration cannot bypass it.</span></div></section>
<section class="robot-stack-wrap"><div class="stack-header"><span>MISSION → ON-DEVICE RUNTIME → FEEDBACK</span><button id="robotTrace">▶ Trace one task</button></div>${Object.entries(robotLayers).map(([k,v])=>robotLane(k,v)).join('')}</section>
<aside class="robot-inspector"><span class="eyebrow" id="robotDetailKind">GROUND / LAYER 01</span><h2 id="robotDetailTitle">${e(robotLayers.ground[0].name)}</h2><p id="robotDetailCopy">${e(robotLayers.ground[0].detail)}</p><div class="contract-pair"><article><span>INPUT</span><p id="robotDetailInput">${e(robotLayers.ground[0].input)}</p></article><article><span>OUTPUT</span><p id="robotDetailOutput">${e(robotLayers.ground[0].output)}</p></article></div><div id="robotTech" class="tech-chips"></div><div id="robotPartners" class="robot-partners"></div></aside>
</div></section>`;
const roboticsPage=`${hero('03 / ROBOTICS STACK','The robot has the final say.','The enterprise asks for a skill. The embodiment decides whether it can safely execute now. Switch between ground robot, drone and manipulator to see how the local stack changes.')}${robotVisual}<section class="control-boundary section-block" data-reveal><span class="eyebrow">CRITICAL SYSTEM BOUNDARY</span><h2>A natural-language goal is not a motor command.</h2><div class="boundary-sequence"><span>goal</span><i>→</i><span>mission</span><i>→</i><span>bounded skill</span><i>→</i><b>local runtime</b><i>→</i><span>actuation</span><i>→</i><span>read-back</span></div><p>Network loss, obstacle appearance, geofence, joint limits and protective stop remain local concerns. Cloud intelligence may recommend; the machine retains the right to refuse.</p></section><section class="robot-partner-rail section-block" data-reveal>${partnerButtons(['alphaz','formant','qualcomm','nav2','moveit','px4','isaac'])}</section>`;

const demoLanding=`<section class="demo-landing" data-reveal><div class="demo-copy"><span class="eyebrow">04 / WORKING SYSTEMS</span><h1>Do not explain the architecture first. Show the loop.</h1><p>Two working simulations make the product contract visible: intent, live state, orchestration, execution, approval and measured feedback.</p></div><div class="demo-posters"><a href="/demos/factory?mode=live" class="demo-poster factory"><span>FACTORY</span><h2>Keep the line running.</h2><p>Cooling anomaly → inspection → approval → recovery → verified flow.</p><div class="mini-scene"><i></i><b>P-204</b><em>R-07</em></div><strong>Launch live demo ↗</strong></a><a href="/demos/city?mode=live" class="demo-poster city"><span>CITY</span><h2>Move traffic. Protect people.</h2><p>Video evidence → shared context → signal plan → survey → verified response.</p><div class="mini-scene"><i></i><b>J-01</b><em>D-01</em></div><strong>Launch live demo ↗</strong></a></div></section><section class="demo-sequence section-block" data-reveal><span class="eyebrow">WHAT ALEX SHOULD SEE IN 60 SECONDS</span><div>${[['1','Ask','Natural-language objective'],['2','Ground','Live world state'],['3','Choose','Mission + executor'],['4','Approve','Exact action scope'],['5','Act','Visible physical execution'],['6','Verify','Before / after evidence']].map(x=>`<article><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>`;

const roadmap=`<section class="roadmap-hero" data-reveal><div><span class="eyebrow">05 / DEPLOYMENT ROADMAP</span><h1>Scale the operating contract, not the pilot.</h1><p>Each phase has a technical deliverable and an exit gate. The proof is that site two is cheaper and faster than site one.</p></div><div class="roadmap-meter" aria-hidden="true"><i></i><span>DISCOVER</span><span>PROVE</span><span>REPEAT</span><span>OPERATE</span></div></section><section class="roadmap-machine" data-reveal><div class="roadmap-tabs" role="tablist">${['Discover','Prove','Repeat','Operate'].map((v,i)=>`<button data-roadmap="${i}" aria-selected="${i===0}"><small>${['0–30 DAYS','31–60 DAYS','61–90 DAYS','SCALE'][i]}</small><b>${v}</b><span>0${i+1}</span></button>`).join('')}</div><div id="roadmapDetail" class="roadmap-detail"></div></section><section class="scale-metrics section-block" data-reveal><article><span>QUALITY</span><b>Verified task success</b><p>Accepted evidence, failed verification, intervention.</p></article><article><span>OPERATIONS</span><b>Time to recovery</b><p>Availability, commissioning effort, exception load.</p></article><article><span>ECONOMICS</span><b>Cost per accepted task</b><p>Compute, human review, support and adapter reuse.</p></article></section>`;

const builder=`<section class="builder-hero" data-reveal><div><span class="eyebrow">06 / ABOUT THE BUILDER</span><h1>I build the architecture, the prototype and the business around it.</h1><p>The through-line is physical-world systems: sensing, video intelligence, connected safety, hands-on GenAI products and now Physical AI product architecture.</p></div><div class="builder-proof"><article><span>SHIPPED</span><b>SpeakMyLingo</b><p>Real-time AI translation app personally built and launched.</p></article><article><span>WON</span><b>Global coding championship</b><p>Prompt engineering and coding under competitive constraints.</p></article></div></section><section class="career-signal section-block" data-reveal><div class="career-line"></div>${[['Tata','Connected worker','Sensors + industrial environments','The first lesson: a signal only matters if the response workflow closes.'],['Airtel','Video intelligence','Edge / cloud + computer vision','The second: a model catalogue is not a product unless onboarding and service work.'],['e&','Connected safety','National-scale physical operations','The third: reliability, authority and field operations dominate after the demo.'],['Now','Physical AI','World state + orchestration + execution','The next step: make the complete closed loop the product.']].map((x,i)=>`<article data-parallax="${.012+i*.004}"><span>0${i+1}</span><div><small>${x[0]} / ${x[1]}</small><h2>${x[2]}</h2><p>${x[3]}</p></div></article>`).join('')}</section><section class="builder-close section-block" data-reveal><div><span class="eyebrow">THE POSITIONING</span><h2>Not a product manager standing outside the technology.</h2><p>A technical product leader who can challenge the architecture, prototype the idea, understand the deployment boundary and still own customer outcome and economics.</p></div><div class="hero-actions">${link('/demos/factory?mode=live','See the working system ↗','primary-link')}${link('/operating-stack','See the architecture →')}</div></section>`;

const pages={
 thesis:shell('thesis','Product thesis','Physical AI product thesis: intent, world state, orchestration, execution and evidence.',thesis,'page-thesis'),
 'operating-stack':shell('operating-stack','Reference stack','Deep multi-vendor reference architecture with proposed partners and integration boundaries.',operating,'page-reference'),
 'world-model':shell('world-model','World model','Operational world state, episode memory and action-conditioned prediction architecture.',worldPage,'page-world'),
 robotics:shell('robotics','Robotics stack','Embodiment-specific robotics architecture for ground robots, drones and manipulators.',roboticsPage,'page-robotics'),
 demos:shell('demos','Live demonstrations','Factory and city Physical AI working simulations.',demoLanding,'page-demos'),
 roadmap:shell('roadmap','Deployment roadmap','Production roadmap for repeatable Physical AI deployment.',roadmap,'page-roadmap'),
 'why-ajay':shell('why-ajay','About the builder','Hands-on technical product leadership narrative.',builder,'page-builder')
};

await fs.mkdir('public/pages',{recursive:true});
for(const [slug,html] of Object.entries(pages)) await fs.writeFile(`public/pages/${slug}.html`,html);
await fs.writeFile('public/architecture-catalog.json',JSON.stringify({nav,partners,partnerDepth,reference,referenceModules,integrationRail,robotLayers,world,cases,pageStory,thesisBets}));
const rel=JSON.parse(await fs.readFile('public/release.json','utf8'));rel.release='2026-10-04.7';rel.features=[...new Set([...(rel.features||[]),'distinct-page-stories','deep-partner-architecture','page-specific-motion','reference-blueprint'])];await fs.writeFile('public/release.json',JSON.stringify(rel));
console.log('Seven distinct production narratives generated; live demo pages remain protected by prepare-showcase integrity checks.');
