export const nav=[['/thesis','Thesis'],['/operating-stack','Reference stack'],['/world-model','World model'],['/robotics','Robotics stack'],['/demos','Demos'],['/roadmap','Roadmap'],['/why-ajay','About the builder']];
const partner=(name,role,url,fit,check)=>({name,role,url,fit,check});
export const partners={
 alphaz:partner('AlphaZ','Field robotics & autonomy','https://alpha-z.ai/','Candidate for construction, security and inspection execution. Keep its native autonomy behind a capability adapter.','Confirm supported robot models, mission API, feedback, cancellation and recovery semantics.'),
 formant:partner('Formant','Fleet operations & orchestration','https://www.formant.ai/fleet-orchestration','Candidate for multi-vendor fleet visibility, assignment and operator intervention. Decide explicitly which mission functions to buy rather than duplicate.','Validate tenant boundaries, command permissions, telemetry export and the division of orchestration ownership.'),
 qualcomm:partner('Qualcomm Dragonwing','Edge compute & robotics software','https://www.qualcomm.com/news/onq/2026/06/dragonwing-iq10-robotics-reference-design','Candidate compute foundation for on-device sensing, inference and robotics services. Hardware selection follows the workload and power budget.','Validate availability, supported sensors, thermal budget, model runtime and OEM qualification.'),
 levatas:partner('Levatas','Industrial inspection intelligence','https://levatas.com/','Candidate for instrument readings, thermal inspection and asset-condition interpretation behind a versioned perception interface.','Benchmark specialist accuracy and cost against a general VLM on the actual inspection workload.'),
 optelos:partner('Optelos','Visual asset intelligence','https://optelos.com/','Candidate for inspection data, digital-twin context and asset workflows. Return findings to the common entity and evidence contract.','Confirm data export, entity matching, evidence permissions and workflow integration.'),
 observance:partner('Inkers · Observance','Site capture & as-built context','https://www.inkers.ai/observance','Candidate input for LiDAR, visual and thermal site capture, deviation detection and scan-to-BIM evidence.','Validate coordinate frames, capture timestamps, asset IDs and the freshness of imported site state.'),
 kael:partner('Inkers · Kaël','Construction application intelligence','https://www.inkers.ai/','Candidate application layer relating site observations to schedules, drawings and project decisions.','Keep recommendations distinct from authority; confirm source lineage and integration interfaces.'),
 cosmos:partner('NVIDIA Cosmos','World-model & reasoning services','https://docs.nvidia.com/cosmos/latest/introduction.html','Candidate service for physical reasoning and future-observation generation, separate from authoritative operational state.','Validate domain performance, model license, GPU footprint and uncertainty before product use.'),
 isaac:partner('NVIDIA Isaac Sim','Simulation & evaluation','https://docs.isaacsim.omniverse.nvidia.com/latest/index.html','Candidate development environment for robot simulation, sensor testing and synthetic data. Not the runtime controlling this website.','Match simulated sensors and dynamics to the target embodiment and evaluate transfer.'),
 nav2:partner('Nav2','Mobile robot navigation','https://docs.nav2.org/','Reference navigation framework for localization, planning, obstacle handling and behavior-tree execution.','Qualify maps, transforms, footprint, sensors and controller tuning for each robot.'),
 moveit:partner('MoveIt 2','Manipulation planning','https://moveit.picknik.ai/main/doc/concepts/concepts.html','Reference manipulation layer for robot models, motion planning and collision-aware arm execution.','Validate joint limits, tooling, calibration and the native controller interface.'),
 px4:partner('PX4','Local flight control','https://docs.px4.io/main/en/','Reference flight stack with local modes and failsafes. A fleet mission must respect the aircraft operating envelope.','Qualify airframe, link-loss behavior, geofence, docking and approval procedures.')
};
const l=(id,name,tag,summary,input,output,detail,keys=[],tech=[])=>({id,name,tag,summary,input,output,detail,partners:keys,tech});
export const reference=[
 l('intent','Customer & mission intake','OWN','Translate a business request into a bounded goal.','Operator request + asset + authority','Goal contract / target / scope','A natural-language agent, schedule or enterprise event opens the same typed mission. Unknown assets and unsupported actions are rejected before dispatch.',[],['Agent interface','CMMS / BMS events','Goal schema']),
 l('applications','Application services','INTEGRATE','Package an outcome, not a collection of devices.','Goal + domain records','Inspection / patrol / progress workflow','Separate the reusable platform from domain applications. Inspection produces an accepted finding; construction compares as-built evidence with project intent.',['optelos','kael'],['Inspection','Security patrol','Construction progress']),
 l('intelligence','Intelligence services','HYBRID','Interpret evidence and compare candidate actions.','Frames + sensors + shared state','Findings / uncertainty / candidate plan','Route selected evidence to a general multimodal model or a specialist. Neither a caption nor a predicted future is permission to move equipment.',['levatas','cosmos'],['VLM router','Sensor fusion','Prediction']),
 l('orchestration','Cross-fleet orchestration','OWN / BUY','Assign, authorise, recover and verify.','Plan + capabilities + current constraints','Scoped mission / executor / evidence requirements','This layer coordinates across fleets. Choose whether to build the mission service or integrate one; avoid competing sources of authority. Store approval scope and retry identifiers.',['formant'],['Capability registry','Policy','Mission graph']),
 l('native','Native autonomy & fleet platforms','PARTNER','Translate common skills into supported OEM actions.','Approved skill + deadline + target','Native command / progress / read-back','Adapters preserve each platform’s strengths and expose its limits. Native robot autonomy, remote operations and task cancellation are different responsibilities.',['alphaz','formant'],['OEM adapters','Skill APIs','Teleoperation']),
 l('fleets','Physical fleets & edge','PARTNER','Act locally; retain protective control locally.','Validated command + local sensor state','Physical action + independent feedback','Ground robots, drones and fixed infrastructure are executors. Edge compute hosts perception and autonomy; local controllers retain stop and refusal authority.',['qualcomm','px4','nav2'],['Robots','Drones','Infrastructure'])
];
export const robotLayers={
 ground:[
 l('mission','Approved mission','CLOUD / SITE','Inspect asset P-204 and return evidence.','Mission ID + asset + permission','Accepted task + required evidence','The fleet-level goal ends at an explicit skill interface; it does not become direct wheel or joint commands.',['formant'],['Mission contract','Expiry','Cancel']),
 l('skills','Skill runtime','ON ROBOT','Navigate → inspect → report → dock.','Task + capability profile','Bounded skill sequence','A behavior tree or state machine handles success, retry, hold and escalation. A field-autonomy vendor can supply this capability.',['alphaz','nav2'],['Behavior tree','Recovery','Skill status']),
 l('perception','Perception & local state','ON ROBOT','Know the robot pose and inspect the equipment.','Camera / depth / IMU / instrument','Pose + obstacle map + reading','Local state is optimized for movement and inspection. Asset evidence is synchronized into the operational world model with time and source.',['levatas','qualcomm'],['Localization','Costmap','Gauge / thermal']),
 l('planning','Navigation & motion','ON ROBOT','Convert a destination into feasible motion.','Goal pose + footprint + constraints','Path / velocity request','Nav2 is a reference for local navigation. It is not a replacement for fleet scheduling or independent protective hardware.',['nav2'],['ROS 2 actions','Planner','Controller']),
 l('control','Control & safety boundary','LOCAL CONTROL','Validate execution at the machine.','Setpoint + actuator limits + watchdog','Motor control / hold / stop','Loss of network or a new obstacle must have a qualified local response. An external agent cannot bypass this boundary.',[],['Watchdog','Interlocks','E-stop']),
 l('feedback','Feedback & fleet lifecycle','ROBOT → CLOUD','Measure the result and improve the next deployment.','Sensor read-back + intervention + task log','Outcome evidence / health / update record','Keep task evidence separate from command acknowledgement. Version software and models, stage updates and retain rollback.',['formant','isaac'],['Telemetry','OTA / rollback','Episode export'])
 ],
 drone:[
 l('mission','Survey mission','CLOUD / SITE','Specify target, permitted region and return conditions.','Area + survey goal + authority','Scoped flight task','A drone mission includes a capture objective and return behavior. A weather feed alone is not flight clearance.',['formant'],['Mission plan','Flight envelope','Return policy']),
 l('skills','Companion autonomy','ON AIRCRAFT','Survey → capture → return → dock.','Approved mission + payload capability','Waypoints / capture plan','High-level autonomy runs on the companion computer. The aircraft controller continues to own flight stabilization and failsafes.',['qualcomm'],['Mission executor','Payload control','Link monitoring']),
 l('perception','Navigation & payload sensing','ON AIRCRAFT','Separate flight sensing from inspection evidence.','GNSS / IMU / camera / depth','Pose estimate + source-labelled imagery','Inspection outputs can go to a specialist or a general VLM. They do not replace the flight-state estimator.',['levatas','observance'],['Visual / inertial state','Image capture','Evidence time']),
 l('planning','Autopilot interface','ON AIRCRAFT','Send only supported mission and setpoint requests.','Waypoints + local constraints','Accepted mode / setpoint feedback','Use a qualified autopilot interface. Native mode transitions, link loss and return-to-home behavior remain explicit.',['px4'],['MAVLink / MAVSDK','Mission mode','Setpoint limits']),
 l('control','Flight control & failsafes','LOCAL CONTROL','Stabilise, contain and land safely.','State estimate + flight limits','Attitude / motor output / failsafe','The aircraft must retain local geofence and failsafe behavior. Remote approval never removes its protective limits.',['px4'],['Estimator','Flight controller','Geofence']),
 l('feedback','Evidence, dock & readiness','AIRCRAFT → CLOUD','Close the survey and prepare the next sortie.','Imagery + mission log + dock status','Accepted evidence / charge / readiness','Check returned evidence, vehicle status and docking separately. A completed waypoint is not an accepted inspection.',['optelos','formant'],['Survey evidence','Dock state','Maintenance'])
 ],
 arm:[
 l('mission','Manipulation request','CLOUD / SITE','Name the object, goal and permission boundary.','Object identity + task + authority','Scoped manipulation goal','A high-level request is grounded before a robot policy or motion planner proposes movement.',[],['Object frame','Task scope','Permission']),
 l('skills','Task & policy selection','ON ROBOT','Choose a qualified skill for this arm and tool.','Task + embodiment + tool profile','Skill / trajectory proposal','Use a learned policy only within its evaluated task distribution. A VLA is an optional skill provider, not the safety controller.',['qualcomm'],['Skill library','VLA adapter','Fallback']),
 l('perception','Scene & contact understanding','ON ROBOT','Resolve the object, obstacles and contact state.','RGB-D + joint state + force','Planning scene + pose estimate','Coordinate transforms, calibration and proprioception bind what the camera sees to what the arm can reach.',[],['RGB-D','Transforms','Force / torque']),
 l('planning','Motion & collision planning','ON ROBOT','Find a feasible motion for this embodiment.','Target pose + scene + joint limits','Collision-checked trajectory','MoveIt 2 is a reference manipulation framework. The arm model and tool geometry are part of the product configuration.',['moveit'],['IK','Planning scene','Trajectory']),
 l('control','Servo & protective control','LOCAL CONTROL','Enforce joint, torque and workspace limits.','Trajectory + hardware feedback','Actuation / protective stop','Native control and qualified protective systems remain responsible for physical limits; cloud orchestration cannot disable them.',[],['Servo','Force limits','Protective stop']),
 l('feedback','Task verification & learning','ROBOT → CLOUD','Check the object outcome, not only arm motion.','Final scene + contact + execution trace','Accepted task / exception / episode','Use independent observation to check completion. Retain failed grasps and interventions as evaluation data.',['isaac','formant'],['Outcome check','Episode dataset','Policy evaluation'])
 ]};
export const world=[
 l('observations','Observations','OBSERVED','Capture evidence with its source and timestamp.','Camera frame / sensor measurement','Observation envelope','An observation retains source, capture time, unit or coordinate frame, quality and evidence URI. It may expire; re-reading it does not make it fresh.',['observance'],['Source','Time','Freshness']),
 l('entities','Entity & spatial binding','RESOLVED','Attach a signal to the right physical object.','Observation + asset registry + transform','Persistent entity and relationship','P-204, V-12 and SB-02 must mean the same objects across cameras, robot tasks and maintenance records. A 3D mesh alone is not that identity.',[],['Entity IDs','Relationships','Transforms']),
 l('state','Operational world state','CURRENT BELIEF','Maintain a useful, uncertainty-aware account.','Bound observations + history','Current facts / constraints / unknowns','Keep observed and inferred state separate. Missing or contradictory evidence becomes an explicit uncertainty, not an invented normal reading.',[],['Entity graph','Confidence','TTL']),
 l('memory','Episode memory','RECORDED','Remember the decision and its outcome together.','Before state + action + intervention + result','Replayable episode','Store the mission, policy version, evidence and outcome in one history. Permissions and retention follow the data, not just the dashboard.',['formant','optelos'],['Event store','Lineage','Replay']),
 l('prediction','Prediction service','PREDICTED','Compare possible futures without rewriting facts.','State + candidate action + model version','Projected outcome + assumptions','A learned world model predicts future observations. The operational graph records the current evidence. They complement one another and remain distinct.',['cosmos','isaac'],['Action conditioning','Horizon','Uncertainty']),
 l('decision','Decision & feedback interface','GOVERNED','Return context to a planner; take evidence back.','Facts + predictions + authority','Mission inputs / verified state update','The world model does not directly actuate. A governed mission layer authorises action, and executor feedback updates the next state.',[],['State API','Mission link','Evidence contract'])
];
export const cases={inspection:{label:'Industrial inspection',goal:'Inspect P-204 and recover cooling with approval.',asset:'P-204',application:'Accepted maintenance finding',intelligence:'Gauge + thermal interpretation',skill:'Inspect → isolate → standby',evidence:'Instrument reading + valve feedback'},patrol:{label:'Security patrol',goal:'Inspect perimeter sector N-02; escalate exceptions.',asset:'N-02',application:'Verified security exception',intelligence:'Scene interpretation + change detection',skill:'Patrol → observe → return',evidence:'Geotagged scene + operator decision'},construction:{label:'Construction progress',goal:'Compare zone C-03 with the latest approved plan.',asset:'C-03',application:'As-built deviation report',intelligence:'Scan / image to asset alignment',skill:'Capture → compare → flag',evidence:'Timestamped capture + plan reference'}};
