import fs from 'node:fs/promises';
const read=p=>fs.readFile(p,'utf8');
const model=(kind,cls='')=>`<div class="engineering-view context-model ${cls}" data-machine-view="${kind}" data-scroll-model><div class="model-top"><span class="model-label">Loading spatial model…</span><button data-model-home>Reset view</button></div><div class="model-foot"><span>Scroll to reveal context · drag to orbit</span><span>Illustrative 3D geometry</span></div></div>`;
const roles=[['agent','Reasoning agent','Interpret the request. Decide what evidence is missing.','Goal + world query → a grounded plan'],['world','World model','Connect geometry, observations and operational history.','Place + time + relationships → current context'],['mission','Mission orchestration','Assign a permitted task and verify the result.','Plan + authority → execution + evidence']];
const roleStrip=()=>`<section class="context-roles" aria-label="Three product responsibilities">${roles.map(([id,title,p,io],i)=>`<button data-role="${id}" aria-pressed="${i===0}"><span>0${i+1}</span><div><h3>${title}</h3><p>${p}</p><small>${io}</small></div><b>↗</b></button>`).join('')}</section>`;
function story(type){const world=type==='world';return `<section class="context-story" id="context-story" data-context-story><div class="context-chapters"><article data-context-chapter="0"><span class="eyebrow">01 / ${world?'PLACE & IDENTITY':'THE PHYSICAL ESTATE'}</span><h2>${world?'The pump belongs to a system.':'Start with a place, not an alert.'}</h2><p>${world?'P-204 supplies the production area. V-12 isolates its duty circuit. SB-02 is an independent backup. Those relationships survive a change of sensor or robot.':'A building has people, equipment, cameras and routes. A request must refer to the same objects across all of them.'}</p><small>${world?'Geometry · entity IDs · dependencies':'Facility · mobile inspector · connected systems'}</small></article><article data-context-chapter="1"><span class="eyebrow">02 / ${world?'STATE & MEMORY':'SHARED UNDERSTANDING'}</span><h2>${world?'Remember what changed.':'Give the agent something reliable to reason from.'}</h2><p>${world?'Measurements retain their source and time. An inspection adds evidence. An approved intervention becomes a new episode—not a rewrite of the past.':'The world model combines spatial relationships, current observations and history. The agent can ask what changed, what it affects and which evidence is still missing.'}</p><small>${world?'Observed → recorded → compared':'Observation → entity → state → memory'}</small></article><article data-context-chapter="2"><span class="eyebrow">03 / ${world?'PREDICTION & ACTION':'GOVERNED RESPONSE'}</span><h2>${world?'Compare a future. Verify an outcome.':'Coordinate the response. Keep the evidence.'}</h2><p>${world?'Prediction estimates a candidate outcome. Orchestration requests permission and dispatches the task. Independent read-back updates the next state.':'Mission orchestration turns the plan into a task for a robot, infrastructure controller or person. The local executor can refuse; returned evidence closes the loop.'}</p><small>${world?'Current facts ≠ predicted futures':'Plan → permission → executor → verified result'}</small></article></div><div class="context-scene-wrap">${model(world?'world-context':'estate-context')}<div class="context-scene-caption"><span id="contextSceneTag">PHYSICAL CONTEXT</span><strong id="contextSceneTitle">${world?'Production area · duty circuit · standby supply':'One estate. Shared context. Different executors.'}</strong><p id="contextSceneNote">${world?'The highlighted equipment supports the production area, not an isolated dashboard.':'A spatial model connects the building, its equipment and the inspection route.'}</p></div><div class="context-layer-control"><label for="contextDepth">Reveal layers</label><input id="contextDepth" type="range" min="0" max="100" value="0" aria-label="Reveal spatial and mission layers"><button id="contextFollow">Follow scroll</button></div></div></section>`;}
const roleDetail=`<section class="context-role-detail" id="contextRoleDetail"><div><span class="eyebrow" id="roleEyebrow">REASONING AGENT</span><h2 id="roleTitle">A request is not yet a command.</h2><p id="roleDescription">Resolve the target, query current and historical evidence, ask for missing information and propose a bounded plan. Permissions belong to the mission service.</p></div><dl><div><dt>READS</dt><dd id="roleReads">Goal, spatial context, evidence freshness and capability limits.</dd></div><div><dt>RETURNS</dt><dd id="roleReturns">A plan with cited evidence, assumptions and required approval.</dd></div><div><dt>DOES NOT OWN</dt><dd id="roleBoundary">Authoritative sensor facts, operator authority or motor control.</dd></div></dl></section>`;
const worldTimeline=`<section class="context-history" aria-label="State over time"><div><span class="eyebrow">ONE EPISODE / THREE STATES</span><h3>The record survives the repair.</h3><p>Snapshots below are captured from this browser scenario. Future checkpoints remain empty until the corresponding event occurs.</p></div><div class="context-history-cards"><button data-context-snapshot="before"><small>BEFORE / FIRST OBSERVATION</small><strong data-snapshot-value="before">Waiting for a sample</strong><span>Original evidence retained.</span></button><button data-context-snapshot="approved"><small>INTERVENTION / APPROVAL</small><strong data-snapshot-value="approved">Not yet authorised</strong><span>Who may change which assets.</span></button><button data-context-snapshot="after"><small>AFTER / VERIFIED RESULT</small><strong data-snapshot-value="after">No result yet</strong><span>Observed outcome, not prediction.</span></button></div><p id="contextSnapshotDetail" role="status">Run recovery below, approve the scoped action, then compare its recorded checkpoints.</p></section>`;
const queryPanel=`<section class="context-agent-example"><div><span class="eyebrow">AGENT / GROUNDED IN THIS EXAMPLE</span><h3>Ask about the current state.</h3><p>These three questions read the running scenario. This is a bounded demonstrator, not an undisclosed model API.</p></div><div><div class="context-queries"><button data-context-query="changed">What changed?</button><button data-context-query="impact">What does it affect?</button><button data-context-query="act">Can we act?</button></div><p id="contextAnswer" role="status">Choose a question after reading the source-labelled measurements below.</p><small id="contextAnswerSource">Basis: the browser's operational state and mission record.</small></div></section>`;
const catalog=JSON.parse(await read('public/light-catalog.json'));
const added={
 'intent-agent':{id:'intent-agent',row:0,title:'Reasoning Agent',subtitle:'Grounded intent & planning',body:'Converts an operator request into a plan grounded in spatial context, current evidence and operational history. The agent queries the World Model; the Mission Orchestrator owns permission and dispatch.',chips:['World queries','Evidence references','Task planning'],input:'Goal + entity references + current/historical world state + capability catalog',output:'Plan + evidence references + uncertainty + requested approval',detail:'Proposed agent tools: query_state, retrieve_episode, compare_candidate, propose_mission. Tool results retain source, capture time and version. Missing evidence becomes a question or inspection request. No direct device commands; no invented measurements.'},
 'intelligence-1':{id:'intelligence-1',row:2,title:'World Model',subtitle:'Spatial state & episode memory',body:'Shared context across geometry, people, places, equipment, telemetry and workflow history. The operational state is distinct from the predictive models that consume it.',chips:['Entity graph','State history','Freshness'],input:'Spatial geometry + timestamped observations + asset relationships + action/outcome episodes',output:'Current state + historical query + uncertainty + provenance',detail:'Own entity resolution, coordinate frames, event time, source TTL and episode lineage. Read APIs expose now, at-time and changes-since views. A prediction is stored with its assumptions and model version; it cannot overwrite measured state.'},
 'intelligence-2':{id:'intelligence-2',row:2,title:'Reasoning & Prediction Services',subtitle:'Replaceable model interfaces',body:'A general multimodal model interprets selected evidence; a dynamics model compares candidate futures. Domain specialists remain where their evaluated accuracy, latency or offline performance is better.',chips:['VLM routing','Candidate rollouts','Evaluation'],input:'Versioned context snapshot + selected evidence + optional candidate actions',output:'Findings or predicted trajectories with uncertainty and evidence references',detail:'The model service is replaceable. The World Model holds the operational record. The Reasoning Agent decides which service to consult. Model output remains a proposal until mission policy and independent feedback validate it.',partner:'cosmos'},
 'orchestration-0':{id:'orchestration-0',row:3,title:'Mission Orchestration',subtitle:'Governed enterprise execution',body:'Turns a grounded plan into a scoped mission across native fleet platforms, infrastructure and human workflows. Coordinates assignment, approval, progress, recovery and outcome acceptance.',chips:['Approvals','Cross-fleet tasks','Evidence'],input:'Proposed plan + principal + capabilities + current world constraints',output:'Authorised tasks + progress + accepted evidence + episode update',detail:'Keep a single mission authority. Check permissions against current state; expire stale plans; retain idempotency, cancellation and recovery semantics. Local controllers enforce their operating limits. Completed evidence updates the World Model and informs the agent.'}
};
Object.assign(catalog.nodeRegistry,added);
const button=m=>`<button class="arch-module context-core-module" data-module="${m.id}" data-node="${m.id}"><small>${m.subtitle}</small><strong>${m.title}</strong><span>${m.chips.join(' · ')}</span><em data-node-state="${m.id}">Inspect ↗</em></button>`;
for(const slug of ['thesis','world-model','operating-stack']){
 let h=await read(`public/pages/${slug}.html`);
 h=h.replace('</head>','<link rel="stylesheet" href="/product/context-design.css?v=1"><script type="module" src="/product/context-ui.js?v=1"></script></head>');
 if(slug==='thesis'){
  h=h.replace(/<section class="product-heading">[\s\S]*?<\/section>/,`<header class="context-heading"><span class="eyebrow">PRODUCT THESIS / SPATIAL CONTEXT TO PHYSICAL ACTION</span><h1>One operating layer for the physical world.</h1><p>The agent interprets a request. The world model supplies context and memory. Orchestration sends a permitted task to a robot, system or person—and records the result.</p><div><a class="primary" href="/operating-stack">Explore the full stack ↗</a><a href="/demos/factory?mode=live">Watch it work →</a></div></header>${roleStrip()}${story('thesis')}${roleDetail}`);
  h=h.replace(/<div class="engineering-view thesis-model"[\s\S]*?<div class="model-foot">[\s\S]*?<\/div><\/div>/,'');
  h=h.replace('Follow one cooling incident.','Put the three roles to work.').replace('Click each decision. The state on the right follows the running browser simulation—not a slide timer.','Example: cooling has failed in a production area. The agent investigates, the world model retains the evidence, and orchestration requests a scoped recovery.');
  h=h.replace('<div class="live-card">','<div class="live-card"><div class="context-example-label">FACTORY EXAMPLE · P-204 DUTY CIRCUIT / SB-02 BACKUP</div>');
 }
 if(slug==='world-model'){
  h=h.replace(/<section class="product-heading">[\s\S]*?<\/section>/,`<header class="context-heading"><span class="eyebrow">WORLD MODEL / SPATIAL STATE, MEMORY & PREDICTION</span><h1>A place, its history and its possible futures.</h1><p>A pump is one entity. Its location, dependencies, sensor evidence and maintenance history make it useful context. The world model connects them; the agent reasons from them.</p><div><a class="primary" href="#world-lab">Explore a state change ↓</a><a href="/operating-stack">See where it fits →</a></div></header>${story('world')}`);
  h=h.replace(/<div class="engineering-view world-model-scene"[\s\S]*?<div class="model-foot">[\s\S]*?<\/div><\/div>/,model('world-context','world-lab-context'));
  h=h.replace('<section class="section world-lab" id="world-lab">','<section class="section world-lab" id="world-lab">'+worldTimeline+queryPanel);
  h=h.replace('P-204 / Cooling circuit','A production area has lost cooling.').replace('The browser simulates FT-02 and PT-04. Expire the source to see the planning gate hold. Refresh it to restore an observed state.','P-204 is the duty pump. V-12 isolates it; SB-02 can restore supply. FT-02 measures flow and PT-04 measures pressure. Run the scenario, approve recovery and compare the recorded states.');
  h=h.replace('P-204 · simulate the recovery and inspect each state change.','Simulated recovery · isolate the failed duty circuit and start independent standby.');
 }
 if(slug==='operating-stack'){
  h=h.replace('Six layers. Named partner options. Follow a request down to an executor and the evidence back to the customer.','The Reasoning Agent interprets the goal. The World Model supplies shared spatial state and memory. Mission Orchestration coordinates permitted actions across the partner stack.');
  h=h.replace(/(<div class="arch-band" data-band="0">[\s\S]*?<div class="arch-modules">)/,`$1${button(added['intent-agent'])}`);
  for(const id of ['intelligence-1','intelligence-2','orchestration-0'])h=h.replace(new RegExp(`<button class="arch-module" data-module="${id}"[\\s\\S]*?<\\/button>`),button(added[id]));
  h=h.replace('Perception &amp; reasoning','World state, perception & reasoning').replace('Perception & reasoning</h3>','World state, perception & reasoning</h3>');
  h=h.replace('<div class="architecture-bottom">','<div class="context-architecture-loop"><b>REASONING AGENT</b><span>queries ↔</span><b>WORLD MODEL</b><span>grounds →</span><b>MISSION ORCHESTRATION</b><span>dispatches →</span><b>EXECUTORS</b><span>return evidence ↺</span></div><div class="architecture-bottom">');
 }
 h=h.replace('model-studio.js?v=1','model-studio.js?v=2');
 await fs.writeFile(`public/pages/${slug}.html`,h);
}
await fs.writeFile('public/light-catalog.json',JSON.stringify(catalog));
const r=JSON.parse(await read('public/release.json'));r.release='2026-10-05.4';r.features=[...new Set([...(r.features||[]),'contextual-estate-model','scroll-driven-mesh-layers','reasoning-agent-role','world-model-role','recorded-state-comparison'])];await fs.writeFile('public/release.json',JSON.stringify(r));
console.log('Context and roles applied to Thesis, World Model and Architecture. Demo files untouched.');
