// Scroll changes the design explanation, never the authority to run a mission.
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,narrow=()=>matchMedia('(max-width: 850px)').matches;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,t)=>a+(b-a)*t,smooth=(a,b,v)=>{const t=clamp((v-a)/(b-a));return t*t*(3-2*t)};
const names={alphaz:'AlphaZ',formant:'Formant',qualcomm:'Qualcomm',levatas:'Levatas',optelos:'Optelos',kael:'Inkers Kaël',cosmos:'NVIDIA Cosmos',nav2:'Nav2',px4:'PX4',moveit:'MoveIt 2',isaac:'Isaac Sim'};
const sessions=[];let raf=0;
const vertex='attribute vec2 p;varying vec2 uv;void main(){uv=(p+1.)*.5;gl_Position=vec4(p,0.,1.);}';
const fragment=`precision highp float;uniform sampler2D a;uniform sampler2D b;uniform vec2 crop;uniform vec3 camera;uniform vec2 movement;uniform float blend;uniform vec2 focus;uniform float layerFocus;varying vec2 uv;
vec4 sampleScene(sampler2D source,vec2 q){float depth=smoothstep(.05,.95,1.-q.y);vec2 v=q+movement*(.18+.82*depth);return texture2D(source,clamp(v,vec2(.001),vec2(.999)));}
void main(){vec2 q=(uv-.5)*crop/camera.x+.5+vec2(camera.y,-camera.z);vec4 col=mix(sampleScene(a,q),sampleScene(b,q),blend);float band=exp(-pow((q.y-(1.-focus.y))/.17,2.));col.rgb=mix(col.rgb,vec3(.965,.975,.954),layerFocus*(1.-band)*.085);gl_FragColor=col;}`;
function compile(gl,type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error('Scene shader unavailable');return shader}
function texture(gl,img){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);return t}
const loadedImages=new Map();function loadImage(name){const src=`/art/${name}-${innerWidth<700?'800':'1600'}.webp`;if(loadedImages.has(src))return loadedImages.get(src);const promise=new Promise((resolve,reject)=>{const img=new Image();img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Scene image unavailable'));img.src=src});loadedImages.set(src,promise);return promise}
function requestFrame(){if(!raf&&!document.hidden)raf=requestAnimationFrame(frame)}
function chapter(s,i){if(s.index===i)return;s.index=i;const step=s.config.steps[i],q=sel=>s.root.querySelector(sel);q('[data-story-title]').textContent=step.title;q('[data-story-copy]').textContent=step.copy;q('[data-story-name]').textContent=step.name;q('[data-story-counter]').textContent=`${String(i+1).padStart(2,'0')} / ${String(s.config.steps.length).padStart(2,'0')}`;q('[data-story-tag]').textContent=step.tag;q('[data-story-value]').textContent=step.value;
const partners=q('[data-story-partners]');partners.replaceChildren();if(step.partners?.length){const label=document.createElement('small');label.textContent='PROPOSED';partners.append(label);for(const key of step.partners){const b=document.createElement('button');b.type='button';b.dataset.partner=key;b.textContent=(names[key]||key)+' ↗';partners.append(b)}window.__light?.bindDetails?.(partners)}
const direct=q('[data-story-link]');direct.hidden=!step.link;if(step.link){direct.href=step.link;direct.textContent=step.label}s.root.querySelectorAll('[data-story-step]').forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));const text=q('.story-chapter');text.dataset.changing='false';requestAnimationFrame(()=>text.dataset.changing='true');s.root.dataset.chapter=String(i);s.visual.dataset.chapter=String(i);s.visual.setAttribute('aria-label',`${step.name}: ${step.title} Rendered design walkthrough.`);
if(narrow()||reduced){const n=step.camera;s.visual.style.setProperty('--scene-zoom',n[0]);s.visual.style.setProperty('--scene-x',(-n[1]*100)+'%');s.visual.style.setProperty('--scene-y',(-n[2]*100)+'%')}
const fallback=s.visual.querySelector('img');if(s.fallbackAsset!==step.asset){fallback.src=`/art/${step.asset}-${innerWidth<700?'800':'1600'}.webp`;s.visual.querySelector('source')?.remove();s.fallbackAsset=step.asset}
if(s.root.dataset.scrollStory==='roadmap')document.querySelector(`.phase-tabs button[data-phase="${i}"]`)?.click();}
function locate(s){const r=s.root.getBoundingClientRect();s.rect=r;const nh=document.querySelector('.nav')?.getBoundingClientRect().height||76;s.navh=nh;return narrow()||reduced?s.manual:clamp((nh-r.top)/Math.max(1,r.height-s.pin.offsetHeight))}
function frame(){raf=0;let again=false;for(const s of sessions){const target=locate(s),onScreen=s.rect.bottom>0&&s.rect.top<innerHeight;if(!onScreen&&!s.force)continue;s.force=false;s.progress=reduced?target:mix(s.progress,target,.16);if(Math.abs(s.progress-target)>.0002)again=true;const n=s.config.steps.length,position=s.progress*(n-1),left=Math.floor(position),right=Math.min(n-1,left+1),f=position-left,alpha=smooth(.25,.8,f);chapter(s,alpha<.5?left:right);const A=s.config.steps[left],B=s.config.steps[right],ease=smooth(.05,.95,f),camera=A.camera.map((x,i)=>mix(x,B.camera[i],ease)),focus=A.focus.map((x,i)=>mix(x,B.focus[i],ease));s.mx=mix(s.mx,s.pointerX,.1);s.my=mix(s.my,s.pointerY,.1);if(Math.abs(s.mx-s.pointerX)+Math.abs(s.my-s.pointerY)>.003)again=true;const travel=s.progress-.5,mvX=s.mx*.009+travel*.018,mvY=s.my*.006+travel*.017;
if(!reduced){s.visual.style.setProperty('--scene-lift',(travel*-22).toFixed(2)+'px');s.visual.style.setProperty('--scene-yaw',(travel*3+s.mx*.6).toFixed(2)+'deg');s.visual.style.setProperty('--caption-y',(travel*30-s.my*5).toFixed(2)+'px');s.visual.style.setProperty('--caption-x',(-s.mx*9).toFixed(2)+'px')}
s.root.querySelectorAll('[data-story-step]').forEach((b,i)=>b.style.setProperty('--segment',clamp(position-i+1)));s.visual.dataset.parallax=s.progress.toFixed(4)+':'+camera.map(x=>x.toFixed(3)).join(':');s.root.style.setProperty('--story-progress',s.progress.toFixed(4));
if(s.gl&&s.textures.has(A.asset)&&s.textures.has(B.asset)&&!s.lost&&!reduced){const gl=s.gl,r=s.visual.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(w!==s.canvas.width||h!==s.canvas.height){s.canvas.width=w;s.canvas.height=h;gl.viewport(0,0,w,h)}const image=s.images.get(A.asset),imageAR=image.naturalWidth/image.naturalHeight,ar=r.width/r.height;gl.useProgram(s.program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,s.textures.get(A.asset));gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,s.textures.get(B.asset));gl.uniform2f(s.u.crop,ar<imageAR?ar/imageAR:1,ar>imageAR?imageAR/ar:1);gl.uniform3f(s.u.camera,...camera);gl.uniform2f(s.u.movement,mvX,mvY);gl.uniform1f(s.u.blend,A.asset===B.asset?0:alpha);gl.uniform2f(s.u.focus,...focus);gl.uniform1f(s.u.layerFocus,s.root.dataset.scrollStory==='operating-stack'?1:0);gl.drawArrays(gl.TRIANGLES,0,6);s.visual.dataset.webgl='ready'}else{s.visual.style.setProperty('--scene-zoom',camera[0]);s.visual.style.setProperty('--scene-x',(-camera[1]*100).toFixed(2)+'%');s.visual.style.setProperty('--scene-y',(-camera[2]*100).toFixed(2)+'%')}}if(again)requestFrame()}
function go(s,index){index=clamp(index,0,s.config.steps.length-1);const p=index/(s.config.steps.length-1);if(narrow()||reduced){s.manual=p;s.progress=p;s.force=true;chapter(s,index);requestFrame();return}const top=scrollY+s.root.getBoundingClientRect().top-s.navh,travel=s.root.offsetHeight-s.pin.offsetHeight;scrollTo({top:top+travel*p,behavior:'smooth'})}
async function start(root){const config=JSON.parse(root.querySelector('[data-story-config]').textContent),visual=root.querySelector('.story-visual'),s={root,config,visual,pin:root.querySelector('.story-pin'),canvas:visual.querySelector('canvas'),textures:new Map(),images:new Map(),progress:0,index:-1,manual:0,mx:0,my:0,pointerX:0,pointerY:0,force:true,fallbackAsset:config.asset};sessions.push(s);root.querySelectorAll('[data-story-step]').forEach(b=>b.addEventListener('click',()=>go(s,Number(b.dataset.storyStep))));visual.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||reduced)return;const r=visual.getBoundingClientRect();s.pointerX=clamp((e.clientX-r.left)/r.width*2-1,-1,1);s.pointerY=clamp((e.clientY-r.top)/r.height*2-1,-1,1);requestFrame()},{passive:true});visual.addEventListener('pointerleave',()=>{s.pointerX=s.pointerY=0;requestFrame()});chapter(s,0);requestFrame();
try{if(!reduced){const gl=s.canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power',preserveDrawingBuffer:true});if(gl){s.gl=gl;const p=gl.createProgram();gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error('Scene renderer unavailable');s.program=p;gl.useProgram(p);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const location=gl.getAttribLocation(p,'p');gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,2,gl.FLOAT,false,0,0);s.u={};for(const name of ['a','b','crop','camera','movement','blend','focus','layerFocus'])s.u[name]=gl.getUniformLocation(p,name);gl.uniform1i(s.u.a,0);gl.uniform1i(s.u.b,1);for(const name of [...new Set(config.steps.map(x=>x.asset))]){const image=await loadImage(name);s.images.set(name,image);gl.activeTexture(gl.TEXTURE0);s.textures.set(name,texture(gl,image));s.force=true;requestFrame()}s.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();s.lost=true;delete visual.dataset.webgl})}}}catch{delete visual.dataset.webgl;s.gl=null}s.ready=true;root.dataset.storyReady='true';requestFrame()}
function openTarget(hash){if(!hash||hash==='#')return null;let target;try{target=document.querySelector(hash)}catch{return null}if(!target)return null;for(let p=target.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;return target}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const target=openTarget(a.getAttribute('href'));if(!target)return;e.preventDefault();requestAnimationFrame(()=>target.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'}));history.replaceState(null,'',a.getAttribute('href'))});
const nav=document.querySelector('.nav');if(nav)new ResizeObserver(()=>{document.documentElement.style.setProperty('--story-navh',nav.offsetHeight+'px');requestFrame()}).observe(nav);for(const root of document.querySelectorAll('[data-scroll-story]'))start(root);addEventListener('scroll',requestFrame,{passive:true});addEventListener('resize',requestFrame,{passive:true});addEventListener('visibilitychange',()=>{if(!document.hidden)requestFrame()});if(location.hash){openTarget(location.hash);setTimeout(()=>openTarget(location.hash)?.scrollIntoView({block:'start'}),100)}
addEventListener('pagehide',()=>{if(raf)cancelAnimationFrame(raf);for(const s of sessions){if(!s.gl)continue;s.textures.forEach(t=>s.gl.deleteTexture(t));s.gl.deleteProgram(s.program);s.gl.getExtension('WEBGL_lose_context')?.loseContext()}},{once:true});window.__story={go:i=>sessions[0]&&go(sessions[0],i),state:()=>sessions.map(s=>({page:s.root.dataset.scrollStory,chapter:s.index,progress:s.progress,webgl:!!s.gl&&!s.lost,ready:!!s.ready}))};
