import fs from 'node:fs/promises';
import {stories,contracts,sources} from './story.mjs';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const narrative=page=>`<section class="deep-narrative deep-${page}" aria-label="Technical narrative">${stories[page].map(s=>`<article><span class="eyebrow">${s.label}</span><h2>${s.title}</h2><p>${s.body}</p><div><b>DESIGN CHOICE</b><p>${s.decision}</p></div><aside><b>PROVE IT</b><p>${s.proof}</p></aside></article>`).join('')}</section>`;
const lab=page=>{if(!contracts[page])return '';const keys=Object.keys(contracts[page]);return `<section class="contract-lab"><div><span class="eyebrow">INTERFACE DESIGN / ILLUSTRATIVE PAYLOADS</span><h2>Read the contract.<br>Challenge the boundary.</h2><p>Versioned inputs and outputs make the proposed architecture testable. These are examples, not deployed partner API specifications.</p><div class="contract-tabs" role="tablist" aria-label="Contract examples">${keys.map((k,i)=>`<button role="tab" aria-selected="${i===0}" data-contract="${k}">${k.replaceAll('_',' ')}</button>`).join('')}</div></div><div class="code-window"><header><span id="contractName">${keys[0]}.json</span><button id="copyContract">Copy JSON</button></header><pre id="contractCode" tabindex="0">${e(JSON.stringify(contracts[page][keys[0]],null,2))}</pre><small id="copyStatus" role="status"></small></div></section>`;};
const svg=(kind)=>`<div class="depth-visual depth-${kind}" data-parallax=".035"><svg viewBox="0 0 500 180" role="img" aria-label="${kind==='world'?'Evidence resolves to related physical entities':'Mission intent connects to local runtime and feedback'}">${kind==='world'?`<g class="depth-points">${Array.from({length:30},(_,i)=>`<circle cx="${20+i%5*21}" cy="${30+Math.floor(i/5)*23}" r="${i%3+1}"/>`).join('')}</g><path class="depth-signal" d="M135 90H230M277 90L382 37M277 90L382 143"/><circle cx="255" cy="90" r="31"/><circle cx="403" cy="37" r="25"/><circle cx="403" cy="143" r="25"/><text x="255" y="95" text-anchor="middle">P-204</text><text x="403" y="42" text-anchor="middle">V-12</text><text x="403" y="148" text-anchor="middle">SB-02</text>`:`<path class="depth-signal" d="M55 80H435M435 106V150H55V105"/><rect x="24" y="53" width="96" height="54"/><rect x="205" y="53" width="96" height="54"/><rect x="381" y="53" width="96" height="54"/><text x="72" y="76" text-anchor="middle">MISSION</text><text x="72" y="94" text-anchor="middle">AUTHORITY</text><text x="253" y="76" text-anchor="middle">LOCAL</text><text x="253" y="94" text-anchor="middle">RUNTIME</text><text x="429" y="76" text-anchor="middle">PHYSICAL</text><text x="429" y="94" text-anchor="middle">FEEDBACK</text><text x="250" y="173" text-anchor="middle">ONE GOAL · DIFFERENT CONTROL BOUNDARIES</text>`}</svg></div>`;
const diagram=(kind)=>`<svg class="scenario-blueprint" viewBox="0 0 600 250" role="img" aria-label="${kind==='factory'?'Cooling circuit schematic':'Junction survey schematic'}"><path class="blueprint-grid" d="M20 20H580V230H20ZM20 90H580M20 160H580M140 20V230M280 20V230M420 20V230"/>${kind==='factory'?`<path class="depth-signal" d="M55 170H175V75H425V165H555"/><rect x="142" y="118" width="74" height="60"/><circle cx="179" cy="147" r="21"/><path d="M304 59L324 75L304 91ZM343 59L324 75L343 91Z"/><rect x="391" y="134" width="65" height="54"/><text x="178" y="213" text-anchor="middle">P-204 / DUTY</text><text x="324" y="48" text-anchor="middle">V-12</text><text x="425" y="214" text-anchor="middle">SB-02 / STANDBY</text>`:`<path class="road-line" d="M290 22V230M22 130H578"/><path class="depth-signal" d="M75 62H477V200H355"/><g transform="translate(477 62)"><circle r="26"/><path d="M-13 -13L13 13M-13 13L13 -13"/><circle cx="-15" cy="-15" r="6"/><circle cx="15" cy="15" r="6"/><circle cx="15" cy="-15" r="6"/><circle cx="-15" cy="15" r="6"/></g><circle cx="290" cy="130" r="8"/><text x="310" y="116">J-01</text><text x="440" y="112">SURVEY</text><text x="47" y="49">CAM-T01</text>`}</svg>`;
const cost=`<section class="cost-lab"><div><span class="eyebrow">ILLUSTRATIVE UNIT ECONOMICS</span><h2>Count the work the model leaves behind.</h2><p>Cost per accepted outcome includes unsuccessful attempts and human review. Change the assumptions to see their effect.</p><div class="cost-inputs">${[['Attempts','Attempts / day',100,1],['Acceptance','Acceptance (%)',90,1],['Inference','Inference / attempt (AED)',.1,0],['Review','Review minutes / attempt',1.5,0],['Minute','Review cost / minute (AED)',2,0],['Fixed','Fixed daily cost (AED)',150,0]].map(([key,label,value,min])=>`<label>${label}<input id="cost${key}" type="number" min="${min}" ${key==='Acceptance'?'max="100"':''} step="0.1" value="${value}"></label>`).join('')}</div></div><aside><span>AED / ACCEPTED OUTCOME</span><output id="costResult">5.11</output><p id="costBasis">460 AED total / 90 accepted outcomes</p><small>Illustration, not a price or ROI claim. Replace assumptions with measured operational data.</small></aside></section>`;
const appStack=`<section class="app-architecture"><span class="eyebrow">SPEAKMYLINGO / HANDS-ON IMPLEMENTATION</span><h2>From a microphone to a usable conversation.</h2><div><b>iOS client</b><i>→</i><b>WebRTC session</b><i>→</i><b>Short-lived credentials</b><i>→</i><b>Realtime model</b></div><p>Vercel backend · App Attest · RevenueCat entitlements · PostHog instrumentation.</p><p>The product decisions become concrete engineering trade-offs: session recovery, latency, access control, telemetry and operating cost.</p><small>Application and career experience supplied by Ajay. The public Physical Ops Lab prototype is independent of employer implementations.</small></section>`;
const next={'thesis':['/operating-stack','Inspect the multi-vendor reference architecture'],'operating-stack':['/world-model','Understand the shared world state'],'world-model':['/robotics','Follow a grounded task onto the robot'],robotics:['/roadmap','Turn the runtime into a repeatable service'],demos:['/operating-stack','Inspect the contracts behind the experience'],roadmap:['/why-ajay','Meet the builder behind the proposal'],'why-ajay':['/demos/factory?mode=live','See the working product thesis']};
for(const page of Object.keys(next)){
 const file=`public/pages/${page}.html`;let h=await fs.readFile(file,'utf8');
 h=h.replace('</head>','<link rel="stylesheet" href="/page-depth.css"><script type="module" src="/page-depth.js"></script></head>');
 h=h.replace(/<div class="hero-mark"[^>]*>[\s\S]*?<\/div>/,page==='world-model'?svg('world'):page==='robotics'?svg('runtime'):'');
 h=h.replace('Modeled on the multi-layer pattern you shared: applications above intelligence, orchestration above native platforms, then physical fleets—connected by explicit mission and evidence contracts.','Applications sit above intelligence, orchestration above native platforms, then physical fleets—connected by explicit mission and evidence contracts.');
 h=h.replace('WHAT ALEX SHOULD SEE IN 60 SECONDS','ONE OPERATIONAL MISSION / SIX DECISIONS').replace('ILLUSTRATIVE LIVE STATE','ILLUSTRATIVE STATE / NOT LIVE PLANT DATA');
 if(page==='thesis'){h=h.replace(/<section class="bets section-block"[\s\S]*?<\/section>/,narrative(page));const targets=['/operating-stack','/world-model','/operating-stack','/robotics','/world-model'];h=h.replace(/<div class="orbit-node n(\d)">([\s\S]*?)<\/div>/g,(_,i,body)=>`<a class="orbit-node n${i}" href="${targets[Number(i)]}">${body}</a>`);}
 if(page==='operating-stack')h=h.replace(/<section class="ownership section-block"[\s\S]*?<\/section>/,narrative(page));
 if(page==='world-model')h=h.replace(/<section class="world-chapters section-block"[\s\S]*?<\/section>/,narrative(page));
 if(page==='robotics')h=h.replace('</main>',narrative(page)+'</main>');
 if(page==='roadmap')h=h.replace(/<section class="scale-metrics section-block"[\s\S]*?<\/section>/,cost+narrative(page));
 if(page==='why-ajay')h=h.replace(/<section class="builder-close section-block"[\s\S]*?<\/section>/,appStack);
 if(page==='demos'){let n=0;h=h.replace(/<div class="mini-scene">[\s\S]*?<\/div>/g,()=>`<div class="mini-scene blueprint-preview">${diagram(n++===0?'factory':'city')}</div>`);h=h.replace('</main>','<section class="demo-data-boundary"><h2>What is running, and what is proposed.</h2><p>The demos run recorded-video inference, simulated physical state and bounded command workflows. Foundation-model services and the named partner connections on the architecture pages are proposals, not active integrations. No real equipment is connected.</p></section></main>');}
 const refs=sources[page]?`<div class="depth-sources"><span>TECHNICAL REFERENCES</span>${sources[page].map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join('')}</div>`:'';
 h=h.replace('</main>',lab(page)+refs+`<a class="next-chapter" href="${next[page][0]}"><span>CONTINUE THE STORY</span><b>${next[page][1]}</b><i>↗</i></a></main>`);
 h=h.replace('</footer>','<button id="depthMotion" aria-pressed="false">Pause decorative motion</button></footer>');await fs.writeFile(file,h);
}
const cat=JSON.parse(await fs.readFile('public/architecture-catalog.json','utf8'));
cat.partners.qualcomm.url='https://www.qualcomm.com/internet-of-things/solutions/worker-safety';
cat.partners.kael.url='https://www.the-inkers.com/kael';
if(cat.partnerDepth?.alphaz)cat.partnerDepth.alphaz.published=cat.partnerDepth.alphaz.published.filter(x=>!x.includes('2,000'));
await fs.writeFile('public/architecture-catalog.json',JSON.stringify(cat));await fs.writeFile('public/contract-catalog.json',JSON.stringify(contracts));
const rel=JSON.parse(await fs.readFile('public/release.json','utf8'));rel.release='2026-10-04.8';rel.features=[...new Set([...rel.features,'deep-technical-narratives','contract-explorer','deployment-cost-lab','nonrepetitive-visuals'])];await fs.writeFile('public/release.json',JSON.stringify(rel));
