import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://localhost:3003',dir='test-report/final-site';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[],report=[];page.on('pageerror',e=>errors.push(e.message));
try{
const routes=['thesis','operating-stack','world-model','robotics','demos','roadmap','why-ajay'];
for(const route of routes){await page.goto(base+'/'+route,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__pageDepth?.ready);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.hero-mark').count(),0,'Repeated decorative hero remains');assert((await page.locator('main').innerText()).length>900,'Missing page substance');assert.equal(await page.locator('.next-chapter').count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Desktop overflow '+route);await page.screenshot({path:dir+'/'+route+'-desktop.png',fullPage:true});
 if(await page.locator('[data-contract]').count()){const tabs=page.locator('[data-contract]');for(let i=0;i<await tabs.count();i++){await tabs.nth(i).click();const text=await page.locator('#contractCode').innerText();assert.doesNotThrow(()=>JSON.parse(text));}await page.locator('#copyContract').click();assert((await page.locator('#copyStatus').innerText()).length>0);}
 await page.locator('#depthMotion').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('depth-motion-off')));await page.locator('#depthMotion').click();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow '+route);await page.screenshot({path:dir+'/'+route+'-mobile.png',fullPage:true});await page.setViewportSize({width:1366,height:900});report.push(route);
}
await page.goto(base+'/roadmap',{waitUntil:'networkidle'});assert.equal(await page.locator('#costResult').innerText(),'5.11');await page.locator('#costReview').fill('0');assert.equal(await page.locator('#costResult').innerText(),'1.78');await page.locator('#costAcceptance').fill('0');assert.equal(await page.locator('#costResult').innerText(),'—');
await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'/world-model',{waitUntil:'networkidle'});assert(await page.locator('body').evaluate(e=>e.classList.contains('depth-motion-off')));
for(const name of ['factory','city']){const r=await page.request.get(base+'/demos/'+name);assert.equal(r.status(),200);const html=await r.text();assert(html.includes('/room/showcase.js'));assert(!html.includes('/page-depth.css')&&!html.includes('/page-depth.js'));}
assert.deepEqual(errors,[]);console.log('PASS: detailed unique narratives, contract examples, cost sensitivity, reduced motion, desktop/mobile layout and untouched demos.');
}catch(e){await page.screenshot({path:dir+'/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await fs.writeFile(dir+'/report.json',JSON.stringify({pages:report,errors},null,2));await browser.close();}
