import fs from 'node:fs/promises';
import {partners,reference,robotLayers} from './catalog.mjs';
import {referenceModules,partnerDepth,integrationRail} from './depth.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Generated-page transformation: the two working demo pages are deliberately excluded.
const pages=['thesis','operating-stack','world-model','robotics','demos','roadmap','why-ajay'];
const keys={'thesis':'thesis','operating-stack':'reference','world-model':'world','robotics':'robotics','demos':'demos','roadmap':'roadmap','why-ajay':'builder'};
function bounds(s,marker){const at=s.indexOf(marker);if(at<0)throw Error('Missing generated component: '+marker);const start=s.lastIndexOf('<',at),tag=s.slice(start+1).match(/^([\w-]+)/)?.[1];if(!tag)throw Error('Invalid component');const re=new RegExp('<(/?)'+tag+'\\b[^>]*>','g');re.lastIndex=start;let depth=0,m;while((m=re.exec(s))){depth+=m[1]?-1:1;if(depth===0)return[start,re.lastIndex];}throw Error('Unclosed '+marker);}
function replace(s,marker,next){const [a,b]=bounds(s,marker);return s.slice(0,a)+next+s.slice(b);}
const figure=(key,cls='',hotspots='')=>`<figure class="render-scene ${cls}" data-scene="${key}"><div class="render-plane"><picture><source media="(max-width:700px)" srcset="/art/${key}-small.webp"><img src="/art/${key}.webp" width="1672" height="941" decoding="async" alt="Rendered ${key} scene" fetchpriority="high"></picture></div>${hotspots}<figcaption><span>ILLUSTRATIVE 3D SCENE</span><span>Scroll to explore</span></figcaption></figure>`;
const stream=`<div class="system-stream"><span id="serviceState">Checking deployment</span><span id="releaseState">Release —</span><button id="environmentState" type="button">Regional context —</button><button id="motionState" type="button" aria-pressed="false">Motion on</button></div>`;
const runtime=`<section class="mission-runtime" aria-label="Interactive mission state"><div><span class="eyebrow">LOCAL INTERACTIVE SIMULATION</span><h3 id="missionTitle">Cooling circuit · awaiting a goal</h3></div><div class="runtime-values"><span>FLOW<b id="liveFlow">18.0 L/min</b></span><span>PRESSURE<b id="livePressure">9.4 bar</b></span><span>STATE<b id="liveRevision">1</b></span><span>EVIDENCE AGE<b id="liveAge">0.0s</b></span></div><div class="mission-actions"><button data-mission="run" class="primary">Run mission →</button><button data-mission="approve" disabled>Approve recovery</button><button data-mission="pause" disabled>Pause</button><button data-mission="reset">Reset</button><button data-mission="export">Export trace</button></div><p id="missionDecision">Current readings support an inspection, not permission to actuate.</p><ol id="missionEvents" class="mission-events"><li>Fresh observation · FT-02 / PT-04</li></ol></section>`;
const module=(m,i,j)=>`<button class="partner-module" data-module="${i}:${j}"><span>${esc(m.subtitle)}</span><b>${esc(m.title)}</b><p>${esc(m.body)}</p><div>${m.chips.map(c=>`<small>${esc(c)}</small>`).join('')}</div><footer><span data-module-state="${i}:${j}">Proposed interface</span><strong>Inspect ↗</strong></footer></button>`;
const layerKeys=['intent','applications','intelligence','orchestration','native','fleets'];
const layerLabels=['Customer & mission','Domain applications','Intelligence services','Mission orchestration','Native platforms','Physical fleets'];
const blueprint=`<section class="reference-blueprint" id="referenceBlueprint"><div class="blueprint-head"><div><span class="eyebrow">REFERENCE ARCHITECTURE</span><h2>One mission across the stack.</h2><p>Inspect each partner’s responsibility, interface and handoff. The running example keeps its own state, authority and evidence record; no partner API is connected.</p></div></div>${runtime}<div class="reference-layout"><div class="aligned-stack">${layerKeys.map((key,i)=>`<section class="architecture-row" data-ref-band="${i}"><button class="architecture-label" data-ref-layer="${i}"><small>LAYER 0${6-i}</small><b>${layerLabels[i]}</b><span data-layer-state="${i}">Ready</span></button><div class="architecture-band"><header><span>${esc(reference[i].summary)}</span><b data-handoff="${i}">Waiting for handoff</b></header><div class="module-grid module-${key}">${referenceModules[key].map((m,j)=>module(m,i,j)).join('')}</div></div></section>`).join('')}<div class="evidence-return"><span>↑</span><p id="evidenceReturn">Feedback → acceptance check → world state</p><b id="evidenceCount">1 event</b></div></div><aside class="architecture-sidebar"><section class="selected-contract"><span class="eyebrow">SELECTED LAYER</span><h3 id="selectedLayer">Customer & mission</h3><p id="selectedDetail">Resolve the goal, asset and authority before dispatch.</p><dl><dt>INPUT</dt><dd id="selectedInput">Request + asset + scope</dd><dt>OUTPUT</dt><dd id="selectedOutput">A bounded mission</dd></dl><button id="showContract">Inspect typed contract ↗</button></section><div class="integration-rail"><span class="eyebrow">ENTERPRISE INTEGRATIONS</span>${integrationRail.map(([a,b,c],i)=>`<button data-integration="${i}"><b>${esc(a)}</b><span>${esc(b)}</span><small>${esc(c)}</small></button>`).join('')}</div><div class="api-card"><span>PROPOSED MISSION API</span><code>POST /missions<br>GET /missions/{id}<br>WEBHOOK /events</code><p>Idempotency · scope · expiry · read-back</p></div></aside></div></section>`;
const modal=`<aside id="technicalDrawer" class="technical-drawer" hidden aria-label="Technical details"><header><span class="eyebrow" id="technicalKind">DETAIL</span><button id="technicalClose" aria-label="Close details">×</button></header><h2 id="technicalTitle"></h2><div id="technicalBody"></div></aside>`;
for(const slug of pages){const path=`public/pages/${slug}.html`;let html=await fs.readFile(path,'utf8');html=html.replace('<link rel="stylesheet" href="/architecture-explorer.css">','<link rel="stylesheet" href="/architecture-explorer.css"><link rel="stylesheet" href="/atelier/site.css">').replace('<script type="module" src="/architecture-explorer.js"></script>','<script type="module" src="/atelier/site.js"></script>').replace('<script type="module" src="/architecture-motion.js"></script>','');
 html=html.replace(/\sdata-reveal(?=[\s>])/g,'').replace(/\sdata-parallax="[^"]*"/g,'');
 if(slug==='thesis'){html=replace(html,'class="mission-orbit"',figure('thesis','thesis-art'));html=html.replace('Physical AI becomes a product when the loop closes.','From a goal to a verified result.');html=html.replace('<section class="story-ribbon"',`${stream}<section class="story-ribbon"`);const agent=`<section class="intent-workbench"><span class="eyebrow">FOLLOW THE OPERATING LOOP</span><form id="contentAgent"><label for="contentCommand">Agent</label><input id="contentCommand" value="Inspect the cooling fault and prepare a recovery" maxlength="300" aria-label="Ask about the example or request a mission"><button class="primary">Send →</button></form><p id="contentReply">Ask what changed, why an action is held, or request an inspection.</p><small>Bounded command parser · state-grounded answers</small>${runtime}</section>`;html=html.replace('<section class="bets ',agent+'<section class="bets ');}
 if(['operating-stack','world-model','robotics'].includes(slug)){html=replace(html,'class="hero-mark"',figure(keys[slug],'page-art'));html=html.replace('</section>',`</section>${stream}`);}
 if(slug==='operating-stack'){html=replace(html,'class="reference-blueprint"',blueprint);}
 if(slug==='world-model'){const nodes='<button class="asset-hotspot" data-world-node="P-204" style="left:55%;top:61%">P-204</button><button class="asset-hotspot" data-world-node="V-12" style="left:76%;top:54%">V-12</button><button class="asset-hotspot" data-world-node="SB-02" style="left:24%;top:66%">SB-02</button><button class="asset-hotspot" data-world-node="R-07" style="left:42%;top:85%">R-07</button>';html=replace(html,'class="entity-map"',figure('world','entity-art',nodes));html=html.replace('<small id="worldFlowFresh">OBSERVED · sample 001</small>','<small id="worldFlowFresh">LOCAL SIMULATION · sample 001</small><svg viewBox="0 0 300 80" class="live-chart" aria-label="Recent simulated cooling flow"><path id="worldFlowChart" d="M0 60H300"/></svg>');html=html.replace('<p>9.4 bar pressure</p>','<p id="worldPressureValue">9.4 bar pressure</p>');html=html.replace('<span class="eyebrow">ILLUSTRATIVE LIVE STATE</span>','<span class="eyebrow">CONTINUOUS LOCAL SIMULATION</span>');html=html.replace('Select Compare futures.','A candidate is computed from the current source revision.');}
 if(slug==='robotics'){html=replace(html,'class="embodiment-visual"',`<section class="embodiment-visual"><div class="robot-render"><img id="robotArtwork" src="/art/robot-ground.webp" width="635" height="600" alt="Rendered ground inspection robot"><div class="robot-render-state"><span id="robotTask">No task dispatched</span><b id="robotTaskState">READY</b></div></div><div class="robot-progress"><i id="robotTaskProgress"></i></div><div class="robot-telemetry"><span id="robotEnergy">Battery model · 94.0%</span><time id="robotStateTime">—</time></div><div class="boundary-label"><b>LOCAL CONTROL</b><span>The runtime can refuse an invalid request.</span></div><button id="robotApprove" disabled>Approve the bounded task</button><button id="robotStop">Stop task</button><small class="runtime-basis">Interactive runtime model · no connected robot</small></section>`);}
 if(slug==='demos'){html=replace(html,'class="demo-landing"',`<section class="demo-landing"><div class="demo-copy"><span class="eyebrow">WORKING SYSTEMS</span><h1>See the decision.<br>Check the result.</h1><p>Factory recovery and city response. Current state, scoped authority, visible execution and evidence.</p></div>${figure('demos','demo-cover-art')}</section>${stream}<div class="demo-posters"><a href="/demos/factory?mode=live" class="demo-poster factory"><img src="/art/world.webp" width="1672" height="941" alt="Rendered industrial cooling circuit"><span>FACTORY RECOVERY</span><h2>Inspect. Approve. Recover.</h2><p>Investigate the cooling fault and verify restored supply.</p><strong>Open working demo ↗</strong></a><a href="/demos/city?mode=live" class="demo-poster city"><img src="/art/demos.webp" width="1672" height="941" alt="Rendered urban and industrial operations"><span>CITY RESPONSE</span><h2>Observe. Coordinate. Verify.</h2><p>Compare signal plans, preserve the crossing and follow the survey.</p><strong>Open working demo ↗</strong></a></div>`);const depth=`<section class="demo-depth section-block"><span class="eyebrow">INSIDE THE EXISTING DEMOS</span><h2>Open the layer you want to inspect.</h2><div>${[['world','World state','Entity identity, freshness, source evidence and relationships.'],['mission','Orchestration','Task dependencies, scoped approval and recovery conditions.'],['execution','Execution','Robot state, controller read-back and accepted evidence.']].map(([key,title,desc])=>`<button data-demo-depth="${key}"><b>${title}</b><span>${desc}</span><small>Where to find it in the demo ↗</small></button>`).join('')}</div><p>The demo screens and runtimes are unchanged.</p></section>`;html=html.replace('</main>',depth+'</main>');}
 if(slug==='roadmap'){html=replace(html,'class="roadmap-meter"',figure('roadmap','roadmap-art'));html=html.replace('<section class="roadmap-machine"',stream+'<section class="roadmap-machine"');html=html.replace('<div id="roadmapDetail" class="roadmap-detail"></div>','<div id="roadmapDetail" class="roadmap-detail"></div><div class="rollout-review"><span class="eyebrow">REVIEW THE EXIT GATE</span><div id="rolloutChecks"></div><span id="rolloutCount">0 / 3 reviewed</span></div>');}
 if(slug==='why-ajay'){const [a,b]=bounds(html,'class="builder-proof"');const proof=html.slice(a,b);html=replace(html,'class="builder-proof"',figure('builder','builder-art'));html=html.replace('<section class="career-signal"',stream+proof+'<section class="career-signal"');html=html.replace('<section class="builder-close ',`<section class="builder-inspector section-block"><div class="builder-tabs"><button data-builder="app" aria-pressed="true">SpeakMyLingo</button><button data-builder="coding">Coding championship</button><button data-builder="systems">System delivery</button><button data-builder="prototype">This prototype</button></div><article id="builderDetail"></article></section><section class="builder-close `);}
 html=html.replace('</body>',modal+'</body>');html=html.replaceAll('Modelled on','Modeled on');await fs.writeFile(path,html);
}
await fs.mkdir('public/atelier',{recursive:true});await fs.writeFile('public/atelier/catalog.json',JSON.stringify({partners,reference,robotLayers,referenceModules,partnerDepth,integrationRail}));const r=JSON.parse(await fs.readFile('public/release.json','utf8'));r.release='2026-10-05.1';r.features=[...new Set([...(r.features||[]),'light-generated-artwork','depth-parallax','aligned-architecture-rows','stateful-mission-trace','untouched-working-demos'])];await fs.writeFile('public/release.json',JSON.stringify(r));console.log('Seven content pages refined; no working demo page or runtime modified.');
