import fs from 'node:fs/promises';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const step=(name,title,copy,asset,camera,focus,tag,value,partners=[])=>({name,title,copy,asset,camera,focus,tag,value,partners});
const stories={
thesis:{eyebrow:'01 / PRODUCT THESIS',title:'One goal.<br>A verified result.',summary:'Understand the environment. Coordinate the right machine. Prove the outcome.',next:'#operating-loop',cta:'Try the working loop',asset:'thesis',steps:[
step('Understand','First, know what changed.','Bind the observation to an asset, its history and the things it depends on.','thesis',[1.04,0,0],[.42,.42],'INPUT','A signal with time, source and identity'),
step('Decide','A plan is not permission.','Compare the options, select a capable executor and make the approval boundary explicit.','stack',[1.17,-.015,.02],[.55,.53],'DECISION','Goal → grounded plan → scoped approval',['formant']),
step('Act','Give the machine a bounded task.','The local runtime owns movement, protective limits and recovery when the network fails.','robotics',[1.17,.015,.03],[.65,.6],'EXECUTION','One mission. Different embodiments.',['alphaz','qualcomm']),
step('Verify','Finish with evidence.','Check the physical result. Keep the failed asset, intervention and repair need in the record.','world',[1.15,.035,.025],[.62,.66],'OUTCOME','Read-back, not a command acknowledgement')
]},
'operating-stack':{eyebrow:'02 / PHYSICAL AI ARCHITECTURE',title:'One mission.<br>Many specialist systems.',summary:'Own the state, authority and evidence. Integrate the models, fleet platforms and machines.',next:'#architecture',cta:'Inspect partners & interfaces',asset:'stack',steps:[
step('Request','Start with the customer outcome.','A portal, operator or enterprise event opens the same mission—not a different integration for every robot.','stack',[1.12,0,-.08],[.53,.18],'LAYERS 06–05','Customer request → domain workflow',['optelos','kael']),
step('Understand','Make perception replaceable.','Combine sensor evidence and asset context. Route to a general model or a specialist where it earns its place.','stack',[1.27,0,-.01],[.53,.43],'LAYER 04','Observed state + candidate actions',['levatas','cosmos']),
step('Coordinate','Keep one owner of the mission.','Match capability, check authority and manage recovery. Native fleet systems retain their own autonomy.','stack',[1.25,.01,.07],[.53,.59],'LAYERS 03–02','Mission owner → versioned capability adapter',['formant','alphaz','qualcomm']),
step('Verify','Bring the evidence back.','Robots, drones and site controllers return feedback. The customer workflow closes only when its acceptance test passes.','stack',[1.13,0,.12],[.53,.77],'LAYER 01 → CUSTOMER','Physical read-back → accepted outcome',['optelos','formant'])
]},
'world-model':{eyebrow:'03 / WORLD MODEL',title:'What is true now.<br>What could happen next.',summary:'A shared account of assets, observations and uncertainty. Prediction stays separate from fact.',next:'#world-lab',cta:'Test the evidence boundary',asset:'world',steps:[
step('Observe','Keep the source with the signal.','A flow reading needs a sensor, unit and capture time. An old reading must not become a current fact.','world',[1.04,0,0],[.23,.65],'OBSERVATION','FT-02 → flow → capture time'),
step('Connect','Know which equipment it describes.','P-204 is the duty pump. V-12 isolates it. SB-02 supplies a separate standby circuit.','world',[1.21,.02,.07],[.58,.65],'SHARED STATE','Asset identity + physical relationships',['optelos']),
step('Compare','Predict without rewriting reality.','Compare leaving the circuit alone with an approved recovery. A projected improvement is not a measured result.','world',[1.23,.09,-.055],[.81,.28],'PREDICTION','Current state → candidate futures',['cosmos']),
step('Confirm','Let the next observation decide.','A mission needs permission. Its result needs fresh feedback. Missing evidence keeps the answer unknown.','world',[1.07,.01,.02],[.6,.57],'GOVERNANCE','Evidence can inform. It cannot authorise.')
]},
robotics:{eyebrow:'04 / ROBOTICS',title:'One goal.<br>The right embodiment.',summary:'Shared intent and evidence above. Qualified autonomy and protective control on the machine.',next:'#robot-runtime',cta:'Inspect a local runtime',asset:'robotics',steps:[
step('Ground','Inspect where people should not.','A rover combines navigation, local perception and bounded inspection skills. It returns a finding, not just a waypoint.','robotics',[1.24,-.15,.07],[.18,.61],'GROUND ROBOT','Navigate → inspect → return evidence',['alphaz','nav2']),
step('Air','Survey, return and dock.','The companion handles the mission. The flight controller retains stabilization, geofence and lost-link behaviour.','robotics',[1.28,.015,.035],[.54,.64],'DRONE + DOCK','Mission → survey → return → readiness',['qualcomm','px4']),
step('Manipulate','Respect the physical limits.','Object pose, tool geometry and joint limits shape every motion. A language instruction cannot bypass protective control.','robotics',[1.25,.16,.025],[.85,.54],'MANIPULATOR','Locate → plan → execute → verify',['moveit']),
step('Operate','Keep the fleet serviceable.','Version the runtime, preserve rollback and measure intervention. Repeatable tasks matter more than impressive isolated moves.','robotics',[1.04,0,0],[.51,.3],'FLEET OPERATIONS','Health + recovery + accepted outcomes',['formant','isaac'])
]},
demos:{eyebrow:'05 / WORKING SYSTEMS',title:'See the whole loop.<br>Then inspect the stack.',summary:'Two working environments. Give a command, approve the action and check the result.',next:'#demo-choices',cta:'Choose a demonstration',asset:'demos',steps:[
{...step('Factory','Restore cooling.','Inspect the fault, approve the recovery and watch the valve, flow and pressure respond.','demos',[1.24,-.12,.02],[.22,.65],'FACTORY','Inspect → approve → recover → verify'),link:'/demos/factory?mode=live',label:'Run factory ↗'},
{...step('City','Clear the junction.','Join camera evidence, compare a timing change and coordinate a survey without bypassing crossing clearance.','demos',[1.24,.14,.01],[.81,.61],'CITY','Observe → compare → dispatch → verify'),link:'/demos/city?mode=live',label:'Run city ↗'},
{...step('Evidence','Check what really happened.','Recorded footage, simulated controllers and any external context keep their own source labels. Export the decision and result.','demos',[1.04,0,0],[.54,.55],'DATA BOUNDARY','Working simulations—not connected field equipment'),link:'#demo-choices',label:'Choose a demonstration ↓'}
]},
roadmap:{eyebrow:'06 / DELIVERY',title:'Prove one workflow.<br>Make the next site easier.',summary:'A sequence of acceptance gates—not a calendar of features.',next:'#delivery',cta:'Inspect the delivery gates',asset:'roadmap',steps:[
step('Discover','Choose one expensive decision.','Name the operator, the asset and the evidence they will accept. Establish the baseline before choosing the robot.','roadmap',[1.26,-.14,.11],[.17,.76],'GATE 01','Named buyer + task + operating envelope'),
step('Prove','Close the loop on one site.','Integrate one executor. Test approval, cancellation, failure recovery and evidence—not only the happy path.','roadmap',[1.23,-.045,.035],[.39,.6],'GATE 02','Repeatable task + attributable result'),
step('Repeat','Separate configuration from code.','Move the same contract to a new site or machine with a reusable adapter, asset map and commissioning playbook.','roadmap',[1.25,.095,-.04],[.65,.45],'GATE 03','Less custom work for deployment two'),
step('Operate','Earn expansion through service.','Manage fleet readiness, staged updates, exceptions and cost per accepted task. Growth follows repeatability.','roadmap',[1.2,.15,-.085],[.86,.31],'GATE 04','Task quality + service cost + renewal')
]},
'why-ajay':{eyebrow:'07 / AJAY CYRIL',title:'Product judgment.<br>Hands-on execution.',summary:'I build the product, test the architecture and stay accountable for how it works in the field.',next:'#proof',cta:'Inspect the work',asset:'builder',steps:[
step('Build','SpeakMyLingo. Built and launched.','A real-time translation app taught me the practical trade-offs in sessions, latency, authentication and inference cost.','builder',[1.2,.04,.13],[.61,.75],'SHIPPED PRODUCT','Product idea → implementation → deployment'),
step('Test','Prove the idea in code.','Winning a global prompt-engineering championship in coding came from testing model behaviour and fixing failures directly.','builder',[1.23,.10,-.005],[.65,.42],'TECHNICAL PRACTICE','Prototype → measure → debug → iterate'),
step('Scale','Design for the day after launch.','Connected-worker, video and safety systems taught me to include installation, lost connectivity, ownership and recovery in the product.','builder',[1.2,-.12,.065],[.19,.57],'PHYSICAL SYSTEMS','Sensors + edge + service operations'),
step('Own','Turn the stack into a business.','Choose the funded workflow, define the partner boundaries and make the next deployment faster—not just the next presentation better.','builder',[1.05,0,0],[.68,.48],'PRODUCT OWNERSHIP','Customer → architecture → code → operations')
]}};
function wrapTechnical(html,id,summary,sub){const pos=html.indexOf(`id="${id}"`);if(pos<0)return html;const start=html.lastIndexOf('<section',pos),tag=/<\/?section\b[^>]*>/g;let depth=0,end=-1,m;tag.lastIndex=start;while((m=tag.exec(html))){depth+=m[0].startsWith('</')?-1:1;if(depth===0){end=tag.lastIndex;break}}if(end<0)return html;return html.slice(0,start)+`<details class="technical-details" data-technical><summary><span><small>TECHNICAL DETAIL</small><strong>${summary}</strong><em>${sub}</em></span><b aria-hidden="true">+</b></summary>${html.slice(start,end)}</details>`+html.slice(end)}
function narrative(slug,s){const first=s.steps[0];return `<section class="scene-story" data-scroll-story="${slug}" aria-label="${esc(s.eyebrow)} walkthrough"><div class="story-pin"><div class="story-intro"><span class="eyebrow">${s.eyebrow}</span><h1>${s.title}</h1><p>${s.summary}</p></div><div class="story-composition"><div class="story-visual" data-story-visual data-depth-scene data-art="${s.asset}" role="img" aria-label="Rendered ${esc(s.asset)} scene; scrolling changes the view"><picture><source srcset="/art/${s.asset}-800.webp 800w, /art/${s.asset}-1600.webp 1600w" sizes="(max-width:760px) 100vw, 65vw"><img src="/art/${s.asset}-1600.webp" width="1600" height="900" alt="" fetchpriority="high"></picture><canvas aria-hidden="true"></canvas><div class="scene-focus" aria-hidden="true"></div><div class="scene-caption"><small data-story-tag>${first.tag}</small><b data-story-value>${first.value}</b></div><span class="scene-basis">Rendered scene · scroll to explore</span></div><div class="story-editorial"><div class="story-position"><span data-story-counter>01 / ${String(s.steps.length).padStart(2,'0')}</span><span data-story-name>${first.name}</span></div><div class="story-chapter"><h2 data-story-title>${first.title}</h2><p data-story-copy>${first.copy}</p><div class="story-partners" data-story-partners></div><a class="story-direct" data-story-link ${first.link?'':'hidden'} href="${first.link||'#'}">${first.label||''}</a></div><a class="text-link story-skip" href="${s.next}">${s.cta} ↗</a></div></div><div class="story-nav" aria-label="Walkthrough chapters">${s.steps.map((step,i)=>`<button data-story-step="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${step.name}<i></i></button>`).join('')}</div><div class="story-instruction"><span>Scroll to reveal each stage</span><span>or select a chapter</span></div></div><script type="application/json" data-story-config>${JSON.stringify(s).replace(/</g,'\\u003c')}</script></section>`}
export async function refineContentPages(){
for(const file of ['executive-story.css','executive-story.js'])await fs.copyFile(new URL('./'+file,import.meta.url),'public/'+file);
for(const [slug,s]of Object.entries(stories)){const path=`public/pages/${slug}.html`;let html=await fs.readFile(path,'utf8');const start=html.indexOf('<section',html.indexOf('<main')),end=html.indexOf('</section>',start)+10;if(start<0||end<10)throw Error('Missing hero '+slug);html=html.slice(0,start)+narrative(slug,s)+html.slice(end);html=html.replace(/<div class="deployment-strip">[\s\S]*?<\/div>/g,'').replace('class="section demo-cards"','class="section demo-cards" id="demo-choices"');
const map={thesis:['operating-loop','Run a cooling recovery','One named asset. Fresh observations. An explicit approval.'],'operating-stack':['architecture','Six layers. Named partners. Real contracts.','Inspect the full architecture or run a scoped example.'],'world-model':['world-lab','Test what happens when the evidence expires','A local cooling-circuit model—not a live field installation.'],robotics:['robot-runtime','Inside each embodiment','Compare skills, local control and feedback.'],roadmap:['delivery','Delivery gates and acceptance tests','The technical and operating detail behind each phase.']};if(map[slug])html=wrapTechnical(html,...map[slug]);
html=html.replace('LIVE BROWSER SIMULATION','INTERACTIVE EXAMPLE · SIMULATED HERE').replace('LIVE STATE LAB','EVIDENCE WALKTHROUGH').replace('The state on the right follows the running browser simulation—not a slide timer.','The example is pump P-204: cooling flow is too low. Run the recovery, then approve the exact equipment changes.').replace('<p data-mission-note>Source-labelled observations arrive continuously.</p>','<p class="data-context">P-204 needs more than 45 L/min of cooling flow. FT-02 measures flow; PT-04 measures pressure. Both readings come from this browser simulation.</p><p data-mission-note>No action has been authorised.</p>');
if(slug==='operating-stack')html=html.replace('<div class="architecture-live">','<p class="data-context" id="architectureContext">Example: restore the P-204 cooling circuit. The readings below are simulated process measurements, not partner service status. Nothing actuates until approval.</p><div class="architecture-live">');if(slug==='robotics')html=html.replace('<div class="runtime-strip">','<p class="data-context">Illustrative task trace for the selected embodiment. This page is not receiving telemetry from a connected robot.</p><div class="runtime-strip">');
html=html.replace('</head>','<link rel="stylesheet" href="/executive-story.css?v=1"><script type="module" src="/executive-story.js?v=1"></script></head>').replace(/light-site\.(css|js)\?v=10/g,'light-site.$1?v=11');await fs.writeFile(path,html)}
let js=await fs.readFile('public/light-site.js','utf8');js=js.replaceAll("all('[data-depth-scene]')","all('[data-depth-scene]:not([data-story-visual])')").replaceAll("all('[data-phase]').forEach","all('button[data-phase]').forEach").replace("window.__light={getState:","window.__light={bindDetails,getState:").replace("const rect=root.getBoundingClientRect();svg.setAttribute","const rect=root.getBoundingClientRect();if(rect.width<1||rect.height<1)return;svg.setAttribute").replace("'Source-labelled simulated observations arrive continuously.'","'P-204 is below the required cooling flow. Inspect the circuit before permitting any equipment change.'").replace("' · browser sensor'","' · simulated sensor'");
js=js.replace('model.workflow=e.target.value;reset();',"model.workflow=e.target.value;reset();const context=$('architectureContext');if(context)context.textContent={inspection:'Example: restore the P-204 cooling circuit. The readings are simulated process measurements, not partner service status. Equipment changes require approval.',patrol:'Example: inspect perimeter N-02. Follow survey permission, capture and return evidence. This is a simulated mission, not a connected aircraft.',construction:'Example: capture zone C-03 against an approved plan. Follow capture permission and source-labelled evidence. No construction change is being authorised.'}[model.workflow];");await fs.writeFile('public/light-site.js',js);
const rel=JSON.parse(await fs.readFile('public/release.json','utf8'));rel.release='2026-10-05.2';rel.features=[...new Set([...(rel.features||[]),'scroll-led-narrative','contextual-data','executive-overview'])];await fs.writeFile('public/release.json',JSON.stringify(rel));
}
