const c=(label,title,body,decision,proof)=>({label,title,body,decision,proof});
export const stories={
 thesis:[
 c('01 / THE CUSTOMER','Start where uncertainty costs time.','An operator sees an abnormal asset condition but lacks attributable evidence. The first product should connect that asset, request the missing observation and return an accepted maintenance decision. A robot earns its place when mobility improves access, coverage or economics—not because a mobile demo looks impressive.','Sell the inspection outcome, including the review and recovery workflow.','Baseline operator minutes, time to accepted evidence, repeat visits and nuisance events.'),
 c('02 / THE PRODUCT','Make the intelligence replaceable.','Evaluate general multimodal models as the semantic layer. Keep specialist inference where task quality, latency, privacy, offline operation or total cost wins. The stable product boundary is the entity identity, capability description, permission scope and evidence contract—not a particular detector, model or robot.','Own trusted context and the customer outcome. Integrate mature capabilities underneath.','Change the model or executor without rewriting the customer workflow.'),
 c('03 / THE BUSINESS','The second site is the product test.','Store site maps, asset identities, policies and adapter settings as configuration. Retain failed tasks and human interventions as episodes. A new deployment should reuse the mission and acceptance criteria rather than create another one-off dashboard.','Separate repeatable configuration from new engineering work.','Compare commissioning effort, accepted outcomes and cost per task across comparable sites.')],
 'operating-stack':[
 c('OBSERVATION PLANE','Evidence arrives before interpretation.','Adapters normalize source, capture time, receipt time, unit or coordinate frame and quality. A CloudEvents envelope is one candidate for event interoperability; the domain payload still needs its own schema. Keep the raw evidence separate from the current asset projection so a new model can reinterpret a recording without rewriting history.','Candidate services: MQTT / OPC UA ingestion, event log, Postgres / PostGIS entity projection and S3-compatible evidence storage.','Replay a duplicate, late event and stale measurement; check identity, ordering and provenance.'),
 c('COMMAND PLANE','An event is not permission to act.','A typed goal passes asset resolution, capability matching and authority checks. The mission service invokes one native adapter with an operation ID, expiry, preconditions and cancellation semantics. A workflow engine can coordinate retries, but a retried request is not proof of exactly-once physical execution.','Candidate control plane: durable workflow service such as Temporal, a policy decision service such as OPA, and a versioned capability registry.','Lose a command acknowledgement; read device state before deciding whether to repeat the operation.'),
 c('EVIDENCE PLANE','Verify the outcome, not the message.','The executor returns progress, controller read-back and required evidence. Acceptance checks these against the task definition. A successful robot skill and a completed customer outcome remain separate states. Policy, model and adapter versions travel with the episode.','Choose one authority across cross-fleet orchestration and native fleet platforms; avoid competing approval systems.','Exercise cancellation, partial completion, missing evidence and operator escalation before expanding scope.')],
 'world-model':[
 c('GROUNDING','A frame is not a world.','Resolve observations against persistent asset identities and spatial transforms. P-204, its isolation valve and its standby circuit must mean the same objects in video, telemetry, a robot mission and the maintenance record. Capture and receipt times remain separate; a late packet must not silently replace newer evidence.','An entity / spatial graph holds relationships; a time-series store holds measurements; an event log records changes.','For every fact, ask: which source, which object, which time and which coordinate frame?'),
 c('MEMORY','A belief needs a source and a lifespan.','Materialize a current view while retaining original observations. Missing evidence stays unknown; conflicting readings retain both sources. Episodes connect before-state, candidate actions, approval, execution, intervention and resulting evidence. Retrieval helps find relevant episodes; it does not become the authority on current physical state.','Use a vector index for retrieval, not as the sole source of truth for asset state.','Expire a sensor and inject contradictory evidence. The system should expose uncertainty instead of inventing a normal value.'),
 c('PREDICTION','Possible futures are a different data type.','A learned world-model service receives a state snapshot and candidate action, then predicts a future observation or state. Preserve its model version, horizon, assumptions and uncertainty. Compare action-ranking quality with a deterministic baseline on held-out episodes. Generated video never overwrites measured facts.','Keep the operational graph and learned dynamics service separate, joined through a versioned prediction contract.','Measure forecast error, calibration and downstream decision quality by operating condition—not visual plausibility alone.')],
 robotics:[
 c('SKILL CONTRACT','A cloud goal is not a motor command.','A mission names the task, target and required evidence. A local behavior tree, state machine or evaluated policy implements a bounded skill. ROS 2 actions are a reference interface for long-running goals with feedback and cancellation; an OEM adapter must preserve the native platform’s real behavior.','A VLA can supply an action policy inside an evaluated skill. It does not replace native protective control.','Reject unsupported skills, unresolved targets and commands outside the approved scope.'),
 c('LOCAL RESILIENCE','Connectivity loss is a designed state.','Define what each skill does under lost connectivity, stale localization, low energy or an obstructed route. Depending on the qualified machine and task, the local runtime may hold, return, complete a bounded segment or request assistance. A blanket retry is not a recovery design.','Set the operating envelope and recovery policy with the robot and site specialists before deployment.','Interrupt the link during navigation and manipulation; check the local response and evidence reconciliation.'),
 c('LIFECYCLE','Commissioning belongs in the product.','Version calibration, maps, payload, transforms, supported skills, software and models. Stage updates and retain rollback. Simulation and recorded episodes support regression testing but do not independently establish real-world safety. Battery, docking, serviceability and operator recovery determine whether autonomy survives daily use.','Ship a site configuration, adapter qualification record and operator recovery playbook with the runtime.','Track intervention rate, recovery success, update failures, commissioning time and cost per accepted task.')],
 roadmap:[
 c('DEPLOYMENT GATES','Autonomy expands only with evidence.','Start with one funded workflow and a named operational owner. Define the task, acceptance criteria, exclusions and baseline before committing to the robot or model. At each release, evaluate the failure paths as deliberately as the normal path.','Gate progression on accepted outcomes and repeatability, not feature count.','The next site must be easier to commission without lowering the evidence standard.'),
 c('SERVICE ECONOMICS','Count the human work the model leaves behind.','Token price is only one part of the cost. Include capture, decoding, inference, storage, network, human review, remote intervention, field service and failed attempts. Compare cost per accepted outcome against the existing workflow—not against a theoretical fully autonomous alternative.','Use the calculator as an illustrative sensitivity test, not a published price or ROI claim.','Measure actual acceptance rate and review minutes before projecting scale.')],
 'why-ajay':[
 c('SENSING → SYSTEMS','I learned to start at the physical constraint.','Connected-worker products taught me that charging, radios, indoor coverage and who responds to an alert are product decisions. Video intelligence added the challenge of converting a model output into something a customer understands and trusts. Connected safety added operational scale and service responsibility.','Define the entire customer journey, including the handoffs after detection.','Separate the decisions I personally owned from the wider team’s result.'),
 c('ARCHITECTURE → BUILD','I still build the thing.','I personally built and launched SpeakMyLingo, a real-time AI translation app. That means working through live sessions, latency, credentials, entitlements, deployment, telemetry and recovery—not just writing the requirements. I also won a global prompt-engineering championship in coding.','Use prototypes and instrumentation to test assumptions directly.','A shipped application and a working Physical AI prototype complement the product and commercial narrative.'),
 c('BUILD → BUSINESS','The operating model is part of the invention.','The role I want is accountable for the full product: the customer problem, architecture boundaries, engineering priorities, partner choices, deployment model and economics. This independent prototype makes those boundaries concrete while keeping employer implementations private.','Bridge research capability and a service customers can repeatedly operate.','Prove task quality, deployment repeatability and a sustainable support model together.')]
};
export const contracts={
 thesis:{Outcome:{schema:'outcome.v1',mission:'M-204',asset:'P-204',result:'inspection_accepted',evidence:['obs-001','readback-002'],repair_complete:false},Commercial_unit:{unit:'accepted inspection',costs:['platform','inference','review','field_support'],excluded_claim:'unmeasured avoided downtime'}},
 'operating-stack':{Observation:{specversion:'1.0',id:'obs-001',source:'/demo/sensors/FT-02',type:'ops.observation.v1',subject:'P-204',data:{value:18,unit:'L/min',basis:'simulated',ttl_seconds:5}},Mission:{schema:'mission.v1',id:'M-204',asset:'P-204',skill:'inspect_instrument',operation_id:'M-204-inspect-1',authority:'inspection_only',preconditions:['fresh_pose','route_available'],cancel:'hold_and_report'},Capability:{schema:'capability.v1',executor:'R-07',skills:['navigate','inspect_instrument','dock'],adapter:'versioned OEM interface',autonomous_repair:false},Evidence:{schema:'evidence.v1',mission:'M-204',observations:['obs-001'],controller_readback:'required',acceptance:'pending_review',versions:{policy:'p1',adapter:'a1',model:'m1'}}},
 'world-model':{State:{schema:'state.v1',entity:'P-204',flow:{value:18,unit:'L/min',source:'FT-02',basis:'simulation',freshness:'current'},relations:[['V-12','isolates','P-204'],['SB-02','supplies','cooling_header']]},Prediction:{schema:'prediction.v1',snapshot:'state-204-001',candidate:'approved_standby_recovery',horizon_seconds:30,model:'candidate-v1',kind:'predicted_not_observed'},Episode:{schema:'episode.v1',before:'state-204-001',mission:'M-204',approval:'approval-001',actions:['inspect','isolate','standby'],feedback:['position','flow','pressure'],accepted_outcome:'separate_evaluation'}},
 robotics:{Skill_goal:{schema:'skill.v1',id:'inspect-204-1',asset:'P-204',skill:'inspect_instrument',permission:'read_only',deadline_seconds:60,evidence:['reading','image_ref']},Feedback:{goal:'inspect-204-1',status:'held',reason:'route_obstructed',last_safe_pose:'pose-018',command_acknowledged:true,task_complete:false},Deployment_manifest:{robot:'R-07',adapter:'a1',map:'site-demo-v1',calibration:'cal-01',model:'m1',policy:'p1',rollback:'previous_qualified_bundle'}}
};
export const sources={
 'operating-stack':[['CloudEvents envelope','https://cloudevents.io/'],['Temporal workflow service','https://docs.temporal.io/'],['OPA policy decisions','https://www.openpolicyagent.org/docs'],['PostGIS spatial data','https://postgis.net/documentation/']],
 'world-model':[['NVIDIA Cosmos','https://docs.nvidia.com/cosmos/latest/introduction.html'],['Spatial data foundation','https://postgis.net/documentation/']],
 robotics:[['ROS 2 actions','https://docs.ros.org/en/rolling/Concepts/Basic/About-Actions.html'],['Nav2','https://docs.nav2.org/'],['MoveIt 2','https://moveit.picknik.ai/main/doc/concepts/concepts.html'],['PX4','https://docs.px4.io/main/en/']]
};
