export type WeatherContext={status:'available'|'unavailable';basis:'OBSERVED'|'MODELED'|'UNKNOWN';location:string;station:string|null;source:string;sourceUrl:string;observedAt:string|null;fetchedAt:string;temperatureC:number|null;humidityPct:number|null;windMs:number|null;gustMs:number|null;windDirectionDeg:number|null;visibilityM:number|null;rawReport:string|null;refreshSeconds:number;fallback:boolean;notice:string};
const num=(v:unknown):number|null=>typeof v==='number'&&Number.isFinite(v)?v:null;
const inRange=(v:unknown,low:number,high:number)=>{const n=num(v);return n!==null&&n>=low&&n<=high?n:null;};
const timestamp=(v:unknown)=>{const ms=typeof v==='number'?v*1000:typeof v==='string'?Date.parse(v):NaN;return Number.isFinite(ms)?new Date(ms).toISOString():null;};
const BASE={location:'Abu Dhabi',fetchedAt:'',refreshSeconds:300};
export function fromMetar(payload:unknown,now=Date.now()):WeatherContext{
 const list=Array.isArray(payload)?payload:[];const m=list.find(r=>r&&r.icaoId==='OMAA');if(!m)throw Error('OMAA report unavailable');
 const observedAt=timestamp(m.obsTime)||timestamp(m.reportTime);if(!observedAt||Date.parse(observedAt)>now+300000)throw Error('Invalid report timestamp');
 const wind=inRange(m.wspd,0,200);if(wind===null)throw Error('METAR wind unavailable');const gust=inRange(m.wgst,0,250),temp=inRange(m.temp,-70,65),dew=inRange(m.dewp,-80,65);
 let visibilityM:number|null=null;const miles=typeof m.visib==='number'?m.visib:typeof m.visib==='string'?Number.parseFloat(m.visib):NaN;if(Number.isFinite(miles))visibilityM=miles*1609.344;if(/\bCAVOK\b/.test(String(m.rawOb||'')))visibilityM=10000;
 const humidity=temp!==null&&dew!==null?Math.max(0,Math.min(100,Math.round(100*Math.exp(17.625*dew/(243.04+dew)-17.625*temp/(243.04+temp))))):null;
 return{...BASE,status:'available',basis:'OBSERVED',station:'OMAA',source:'NOAA Aviation Weather Center / OMAA METAR',sourceUrl:'https://aviationweather.gov/data/metar/?id=OMAA',observedAt,fetchedAt:new Date(now).toISOString(),temperatureC:temp,humidityPct:humidity,windMs:wind*0.514444,gustMs:gust===null?null:gust*0.514444,windDirectionDeg:inRange(m.wdir,0,360),visibilityM,rawReport:typeof m.rawOb==='string'?m.rawOb.slice(0,1000):null,fallback:false,notice:'Actual Abu Dhabi airport observation. Regional context, not a site sensor. Humidity derived from reported temperature and dew point. No flight clearance.'};
}
export function fromOpenMeteo(payload:unknown,now=Date.now()):WeatherContext{
 const p=payload as {current?:Record<string,unknown>};const c=p?.current;const observedAt=timestamp(c?.time),wind=inRange(c?.wind_speed_10m,0,200);if(!observedAt||wind===null)throw Error('Modeled weather unavailable');
 return{...BASE,status:'available',basis:'MODELED',station:null,source:'Open-Meteo / weather-model estimate',sourceUrl:'https://open-meteo.com/',observedAt,fetchedAt:new Date(now).toISOString(),temperatureC:inRange(c?.temperature_2m,-70,65),humidityPct:inRange(c?.relative_humidity_2m,0,100),windMs:wind,gustMs:inRange(c?.wind_gusts_10m,0,250),windDirectionDeg:inRange(c?.wind_direction_10m,0,360),visibilityM:null,rawReport:null,fallback:true,notice:'Modeled fallback, not a station observation. Open-Meteo / CC BY 4.0. The free endpoint is for non-commercial use. Drone routing defaults to ground when airport evidence is absent.'};
}
export async function getAbuDhabiWeather():Promise<WeatherContext>{
 try{const r=await fetch('https://aviationweather.gov/api/data/metar?ids=OMAA&format=json',{headers:{'User-Agent':'PhysicalIntelligenceDemo/1.0 (Abu Dhabi single-station context)','Accept':'application/json'},next:{revalidate:300},signal:AbortSignal.timeout(5500)});if(!r.ok||r.status===204)throw Error('METAR HTTP '+r.status);const w=fromMetar(await r.json());if(Date.now()-Date.parse(w.observedAt!)<=90*60000)return w;}catch{}
 try{const url='https://api.open-meteo.com/v1/forecast?latitude=24.4539&longitude=54.3773&current=temperature_2m,relative_humidity_2m,wind_speed_10m,wind_gusts_10m,wind_direction_10m&wind_speed_unit=ms&timeformat=unixtime&timezone=UTC';const r=await fetch(url,{next:{revalidate:300},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Weather HTTP '+r.status);return fromOpenMeteo(await r.json());}catch{}
 return{...BASE,status:'unavailable',basis:'UNKNOWN',station:null,source:'No current weather source',sourceUrl:'https://aviationweather.gov/data/api/',observedAt:null,fetchedAt:new Date().toISOString(),temperatureC:null,humidityPct:null,windMs:null,gustMs:null,windDirectionDeg:null,visibilityM:null,rawReport:null,fallback:false,notice:'Both public sources are unavailable. No values have been fabricated. Ground response remains demonstrable.'};
}
