import fs from 'node:fs/promises';
const links=JSON.parse(await fs.readFile('content/navigation.json','utf8'));
const header=active=>`<a class="an-skip" href="#main">Skip to content</a><header class="analog-header"><a class="analog-brand" href="/thesis"><strong>ANALOG</strong><small>PHYSICAL INTELLIGENCE</small></a><nav class="analog-nav" aria-label="Primary navigation">${links.map(l=>`<a href="${l.href}" ${l.href===active?'aria-current="page"':''}>${l.label}</a>`).join('')}</nav></header>`;
const footer='<footer class="an-footer"><span>AJAY CYRIL / INDEPENDENT PRODUCT THESIS</span><span>Reference architecture & simulated operations · Not an official Analog product</span></footer>';
const cards=items=>'<div class="an-grid">'+items.map(([tag,title,copy,url])=>`<article class="an-card"><span class="an-kicker">${tag}</span><h2>${title}</h2><p>${copy}</p>${url?`<a href="${url}">Explore ${title.toLowerCase()} →</a>`:''}</article>`).join('')+'</div>';
const rows=items=>items.map(([title,copy],i)=>`<section class="an-row"><code>0${i+1}</code><b>${title}</b><p>${copy}</p></section>`).join('');
const flow=items=>'<div class="an-flow">'+items.map(x=>'<span>'+x+'</span>').join('')+'</div>';
const pages={
 thesis:{title:'Intelligence becomes valuable when it closes the loop.',label:'Thesis',intro:'A product thesis for Analog: turn fragmented observations, specialist models and heterogeneous machines into accountable outcomes. Build a reusable operating layer between enterprise intent and physical execution.',body:flow(['Observe','Understand','Decide','Authorize','Act','Verify'])+cards([
 ['01 / CUSTOMER VALUE','Sell the outcome','Inspection coverage, time to verified recovery, and reliable service delivery matter more than a robot demonstration. Start with a narrow operational workflow, then earn expansion.'],
 ['02 / PRODUCT BOUNDARY','Own the coordination','Maintain trusted state, govern missions and return evidence. Partner for sensors, perception, fleet platforms and native robot control.','/operating-stack'],
 ['03 / COMPOUNDING ADVANTAGE','Learn from every episode','Every successful or failed mission should improve task templates, policies, exception handling and evaluation data.','/world-model']])+rows([
 ['The initial wedge','Industrial inspection and public-realm response share a valuable pattern: detect an anomaly, ground it in context, route a bounded mission and verify a result. The buyer receives an auditable operational outcome.'],
 ['A reusable product','The same entity schema, mission contract, approval ledger and evidence model should span different OEMs and sites. Deployment adapters change; the customer-facing operating contract remains stable.'],
 ['Measure trust','Track grounded-task success, intervention rate, evidence completeness, time to recovery and cost per completed mission. Report uncertainty and failed verification rather than silently declaring success.']])+`<p class="an-note">This is an independent product proposal by Ajay Cyril. The live demos combine simulated infrastructure with explicitly identified recorded-video inference and external weather context.</p>`},
 'world-model':{title:'A shared account of what is true. And what may happen next.',label:'World Model',intro:'The state, memory and prediction layer. It joins observations to persistent entities, keeps their provenance and freshness, and gives the mission system a testable account of the world.',body:flow(['Sensor event','Entity resolution','Current state','Episode memory','Candidate prediction'])+cards([
 ['STATE','Entities + relationships','An observation is not an asset. Bind frames, gauges and poses to entity IDs, spatial frames, uncertainty, observation time and expiry. Stale evidence becomes unknown.'],
 ['MEMORY','Events + episodes','Retain the observation, chosen policy, approval scope, command, feedback and verification as one time-ordered episode. Replay explains why a mission acted.'],
 ['PREDICTION','Counterfactuals + limits','Compare bounded candidate actions against doing nothing. Preserve model version, horizon, assumptions and uncertainty. A simulated rollout is not an observed outcome.']])+`<table class="an-table"><thead><tr><th>Contract</th><th>Example</th><th>Consumer</th></tr></thead><tbody><tr><td>Observation</td><td>CAM-T01 / frame / source time / freshness</td><td>Entity state</td></tr><tr><td>Relationship</td><td>P-204 feeds cooling header; V-12 isolates duty circuit</td><td>Diagnosis & impact analysis</td></tr><tr><td>Prediction</td><td>45-second traffic rollout or first-order process response</td><td>Mission planner</td></tr><tr><td>Episode</td><td>Goal → decision → approval → feedback → evidence</td><td>Audit & evaluation</td></tr></tbody></table>`+rows([
 ['Write boundary','Sensors and adapters publish observations. The world model records and reconciles them; it does not command actuators.'],
 ['Read boundary','Mission planning queries current constraints and candidate outcomes. Robot runtimes receive explicit skills through adapters, never an implicit world-state mutation.'],
 ['Inspect it working','In the <a href="/demos/factory">factory console</a>, inspect cooling dependencies and the work-order loop. In the <a href="/demos/city">city console</a>, inspect district state, camera provenance and weather-aware routing.']])},
 robotics:{title:'Bounded skills. Local control. Observable execution.',label:'Robotics',intro:'The execution layer translates approved missions into capabilities that each embodiment can actually perform. Fleet coordination belongs above the robot; control loops and emergency stops remain local.',body:flow(['Approved mission','Capability match','Skill runtime','OEM adapter','Local control','Feedback'])+cards([
 ['GROUND','Inspection robots','Navigate a constrained route, inspect a gauge, return evidence and dock. Track battery, localization, controller readiness, connectivity and hold reasons.'],
 ['AIR','Drones + docking','Survey waypoints, stream observations, return to dock. Check weather and operating envelope at dispatch; retain ground-response fallback.'],
 ['INFRASTRUCTURE','Plant + city adapters','Treat valves, pumps and signal controllers as scoped capabilities with explicit authority, interlocks, state read-back and timeout behavior.']])+rows([
 ['Runtime lifecycle','Accepted → executing → held / failed / cancelled → verified. A command acknowledgment is not proof of physical completion. Verification must use feedback independent of the requested target.'],
 ['Integration boundaries','Formant supplies fleet operations and telemetry; OEM stacks retain native controls. AlphaZ is considered for deployed autonomy and reasoning. Qualcomm supplies edge compute and robotics services. The complete multi-vendor arrangement lives in <a href="/operating-stack">Operating Stack</a>.'],
 ['Implemented here','The factory uses MuJoCo dynamics with a kinematic fallback, waypoint planning and a modeled valve skill. The city uses a traffic model, drone waypoints and field response. These are browser simulations, not deployed ROS or hardware integrations.']])+`<p><a href="/lab">Open the physics workbench →</a> · <a href="/demos">Open operations demos →</a></p>`},
 demos:{title:'Two environments. One operating discipline.',label:'Live Demos',intro:'Inspect the world, propose a mission, review authority and follow the evidence. These are interactive reference consoles with simulated assets, recorded camera input and live external context where available.',body:cards([
 ['01 / INDUSTRIAL OPERATIONS','Factory','A multi-zone plant topology: cooling and utilities, process lines, storage, loading access and inspection fleets. Follow a pressure alarm into diagnosis, scoped recovery and verification.','/demos/factory'],
 ['02 / PUBLIC REALM','City','An Abu Dhabi-inspired district operations view: junctions, CCTV, response units, drone routing and regional weather policy. Coordinate incident response across multiple simulated districts.','/demos/city'],
 ['03 / RUNTIME WORKBENCH','Physics lab','Inspect browser physics and low-level execution separately from the operations console.','/lab']])+`<p class="an-note">Data boundaries: plant and city geometry are authored scenarios, not surveyed digital twins. Camera clips are independent recordings, not municipal CCTV. Weather retains its source and timestamp. No real equipment or agency is connected.</p>`},
 roadmap:{title:'Earn trust before scaling autonomy.',label:'Roadmap',intro:'A product sequence organized around evidence and operational readiness. Each stage has an exit criterion, not just a feature list.',body:rows([
 ['0–30 days / Ground','Select one operational wedge with a design partner. Map assets, authority and exceptions. Baseline time to recovery, intervention rate and evidence completeness. Publish the entity and mission contracts.'],
 ['31–60 days / Prove','Deliver one end-to-end workflow with an OEM adapter and human approval. Capture failure episodes. Require reproducible replay, safe cancellation, freshness checks and feedback-based verification.'],
 ['61–90 days / Repeat','Deploy the same mission template to a second site or embodiment. Measure integration effort, policy reuse and recovery quality. Productize recurring exceptions rather than adding one-off demos.'],
 ['Scale / Operate','Introduce fleet service levels, site onboarding, observability, model evaluation and versioned policies. Expand autonomy only where evidence supports the operating envelope.']])+cards([
 ['QUALITY','Verified outcomes','Task success with evidence, unsuccessful verification and operator interventions.'],
 ['OPERATIONS','Recovery + coverage','Time to diagnosis, time to restoration, inspection coverage and incident recurrence.'],
 ['ECONOMICS','Repeatability','Cost per mission, adapter effort, deployment time and recurring service margin.']])},
 'why-ajay':{title:'From sensing to operational ownership.',label:'Why Ajay',intro:'My product perspective connects connected devices, scene understanding, emergency response and multi-vendor Physical AI. The recurring challenge is making fragmented systems deliver a dependable outcome.',body:rows([
 ['Tata / Sense','Worker and connected-device context: start with the signal and the operational problem, then understand what evidence the user can trust.'],
 ['Airtel / Understand','Scene intelligence and enterprise context: translate sensing capabilities into a useful workflow and a clear value proposition.'],
 ['Hassantuk / Respond','Response-loop thinking: detection only matters when ownership, escalation and closure work under real operational constraints.'],
 ['e& / Coordinate','Working through Physical AI architecture and product boundaries across mission intake, perception, orchestration, vendor platforms, drones and ground robots. The focus is how the seams become a reusable operating product.'],
 ['Analog / Productize','Bring that experience into trusted world state, governed missions, partner architecture and measurable outcomes. Own the product boundary and deployment repeatability with engineering and operating partners.']])+`<p class="an-note">Experience narrative supplied by Ajay. Partner diagrams describe architectural roles and product synthesis; they do not imply that every integration is built or commercially deployed.</p><p><a href="/roadmap">See the first 90 days →</a></p>`}
};
await fs.mkdir('public/pages',{recursive:true});
pages['world-model'].body+=`<h2>Industrial reference architecture</h2><p>The proposed production system combines a persistent operational graph with a separate generative model service. NVIDIA Cosmos is the model reference for physical reasoning, future-world generation and simulation-data variation.</p><table class="an-table"><tr><th>Layer</th><th>Production responsibility</th><th>Implemented here</th></tr><tr><td>Observation ingestion</td><td>Timestamped sensor events, calibration, identity and freshness</td><td>Recorded frame inference, simulated gauges, external weather</td></tr><tr><td>Operational belief</td><td>Spatial entities, relationships, uncertainty and contradictory evidence</td><td>Entity graph, dependency links, basis and unknown-state handling</td></tr><tr><td>Persistent memory</td><td>Event storage, replay, retention, lineage and access control</td><td>Session snapshots and exported mission evidence</td></tr><tr><td>Reasoning</td><td>Cosmos-class physical reasoning with evaluation gates</td><td>Bounded intent parser and explicit policy rules</td></tr><tr><td>Prediction</td><td>Conditioned world-model inference and domain validation</td><td>Traffic model and deterministic plant rollouts</td></tr><tr><td>Execution feedback</td><td>Scoped OEM skill adapters and independent completion evidence</td><td>Browser physics, approval gates, verification and cancellation</td></tr></table><p>Cosmos predicts or generates physical-world video; an operational graph retains the authoritative asset state and action ledger. These components complement each other. See <a href="https://docs.nvidia.com/cosmos/latest/introduction.html" target="_blank" rel="noreferrer">NVIDIA’s published Cosmos architecture</a>.</p><p class="an-note">This deployment runs local simulation and perception, not Cosmos weights. GPU inference, durable shared storage, enterprise identity and real OEM adapters remain production integration requirements.</p>`;
for(const [slug,p] of Object.entries(pages)){await fs.writeFile('public/pages/'+slug+'.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.label} | Analog Physical Intelligence</title><meta name="description" content="${p.intro}"><meta property="og:title" content="${p.label} | Analog Physical Intelligence"><link rel="canonical" href="https://analog-physical-intelligence.vercel.app/${slug}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/site.css"></head><body class="analog-page">${header('/'+slug)}<main class="an-main" id="main"><div class="an-crumb"><a href="/thesis">Analog Physical Intelligence</a><span>/ ${p.label}</span></div><span class="an-kicker">${p.label} / Product & operations</span><h1>${p.title}</h1><p class="an-lead">${p.intro}</p>${p.body}</main>${footer}${slug==='thesis'?'<script>const legacy={system:"/operating-stack",roadmap:"/roadmap",fit:"/why-ajay","ninety-day":"/roadmap"};const target=legacy[location.hash.slice(1)];if(target)location.replace(target);</script>':''}</body></html>`);}
const mappings={'/physical-intelligence.html#system':'/operating-stack','/physical-intelligence.html#roadmap':'/roadmap','/physical-intelligence.html#fit':'/why-ajay','/physical-intelligence.html':'/thesis','/physical-ai-stack.html':'/operating-stack','/world-models.html':'/world-model','/robotics-stack.html':'/robotics','/live-system.html':'/demos','/studio.html':'/demos/factory','/city.html':'/demos/city'};
for(const [src,dest,active] of [['physical-ai-stack','operating-stack','/operating-stack'],['studio','factory','/demos'],['city','city','/demos']]){
 let h=await fs.readFile('public/'+src+'.html','utf8');
 for(const [a,b] of Object.entries(mappings))h=h.replaceAll(a,b);
 if(src==='physical-ai-stack')h=h.replace(/<header class="site-header[\s\S]*?<\/header>/,'');
 if(src!=='physical-ai-stack')h=h.replace('<body>','<body class="unified-console">');
 h=h.replace(/<body([^>]*)>/,`<body$1>${header(active)}`);
 h=h.replace('</head>',`<link rel="stylesheet" href="/site.css"><link rel="canonical" href="https://analog-physical-intelligence.vercel.app/${src==='physical-ai-stack'?'operating-stack':'demos/'+dest}">${src!=='physical-ai-stack'?'<link rel="stylesheet" href="/room/operations.css">':''}</head>`);
 h=h.replace(/<title>.*?<\/title>/,`<title>${src==='studio'?'Factory Operations':src==='city'?'Abu Dhabi Operations':'Operating Stack'} | Analog Physical Intelligence</title>`);
 if(src!=='physical-ai-stack')h=h.replace('</body>','<script type="module" src="/room/operations.js"></script><script type="module" src="/room/world-inspector.js"></script></body>').replace('href="#main"','href="#workspace"');
 await fs.writeFile('public/pages/'+dest+'.html',h);
}
console.log('Analog site: canonical routes and shared navigation generated.');
